-- +goose Up
-- +goose StatementBegin
CREATE TABLE velez.shared_volumes
(
    id               INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    node_id          INTEGER REFERENCES velez.nodes (id),
    volume_name      TEXT                                                 NOT NULL,
    service_id       BIGINT REFERENCES velez.services (id)                NOT NULL,

    specification_id INT8 REFERENCES velez.deployment_specifications (id) NULL,
    deployment_id    BIGINT REFERENCES velez.deployments (id)             NULL
);

COMMENT ON COLUMN velez.shared_volumes.specification_id IS
    'You can define a specification to mount a volume to. In case if not null volume will be mounted to all deployments under this specification';
COMMENT ON COLUMN velez.shared_volumes.deployment_id IS
    'You can specify a specific deployment to mount a volume to. In case if not null volume will be mounted only to this deployment';
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE velez.shared_volumes;
-- +goose StatementEnd
