// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.28.3
// source: control_plane_api.proto

package velez_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ControlPlaneAPI_ListServices_FullMethodName   = "/velez_api.ControlPlaneAPI/ListServices"
	ControlPlaneAPI_EnableServices_FullMethodName = "/velez_api.ControlPlaneAPI/EnableServices"
)

// ControlPlaneAPIClient is the client API for ControlPlaneAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControlPlaneAPIClient interface {
	ListServices(ctx context.Context, in *ListServices_Request, opts ...grpc.CallOption) (*ListServices_Response, error)
	EnableServices(ctx context.Context, in *EnableServices_Request, opts ...grpc.CallOption) (*EnableServices_Response, error)
}

type controlPlaneAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewControlPlaneAPIClient(cc grpc.ClientConnInterface) ControlPlaneAPIClient {
	return &controlPlaneAPIClient{cc}
}

func (c *controlPlaneAPIClient) ListServices(ctx context.Context, in *ListServices_Request, opts ...grpc.CallOption) (*ListServices_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServices_Response)
	err := c.cc.Invoke(ctx, ControlPlaneAPI_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlPlaneAPIClient) EnableServices(ctx context.Context, in *EnableServices_Request, opts ...grpc.CallOption) (*EnableServices_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnableServices_Response)
	err := c.cc.Invoke(ctx, ControlPlaneAPI_EnableServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlPlaneAPIServer is the server API for ControlPlaneAPI service.
// All implementations must embed UnimplementedControlPlaneAPIServer
// for forward compatibility.
type ControlPlaneAPIServer interface {
	ListServices(context.Context, *ListServices_Request) (*ListServices_Response, error)
	EnableServices(context.Context, *EnableServices_Request) (*EnableServices_Response, error)
	mustEmbedUnimplementedControlPlaneAPIServer()
}

// UnimplementedControlPlaneAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControlPlaneAPIServer struct{}

func (UnimplementedControlPlaneAPIServer) ListServices(context.Context, *ListServices_Request) (*ListServices_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedControlPlaneAPIServer) EnableServices(context.Context, *EnableServices_Request) (*EnableServices_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method EnableServices not implemented")
}
func (UnimplementedControlPlaneAPIServer) mustEmbedUnimplementedControlPlaneAPIServer() {}
func (UnimplementedControlPlaneAPIServer) testEmbeddedByValue()                         {}

// UnsafeControlPlaneAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControlPlaneAPIServer will
// result in compilation errors.
type UnsafeControlPlaneAPIServer interface {
	mustEmbedUnimplementedControlPlaneAPIServer()
}

func RegisterControlPlaneAPIServer(s grpc.ServiceRegistrar, srv ControlPlaneAPIServer) {
	// If the following call panics, it indicates UnimplementedControlPlaneAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ControlPlaneAPI_ServiceDesc, srv)
}

func _ControlPlaneAPI_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServices_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneAPIServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneAPI_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneAPIServer).ListServices(ctx, req.(*ListServices_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlPlaneAPI_EnableServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableServices_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlPlaneAPIServer).EnableServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ControlPlaneAPI_EnableServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlPlaneAPIServer).EnableServices(ctx, req.(*EnableServices_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ControlPlaneAPI_ServiceDesc is the grpc.ServiceDesc for ControlPlaneAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ControlPlaneAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "velez_api.ControlPlaneAPI",
	HandlerType: (*ControlPlaneAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServices",
			Handler:    _ControlPlaneAPI_ListServices_Handler,
		},
		{
			MethodName: "EnableServices",
			Handler:    _ControlPlaneAPI_EnableServices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "control_plane_api.proto",
}
