// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: grpc/velez_api.proto

package velez_api

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PortBindings_Protocol int32

const (
	PortBindings_unknown PortBindings_Protocol = 0
	PortBindings_tcp     PortBindings_Protocol = 1
	PortBindings_udp     PortBindings_Protocol = 2
)

// Enum value maps for PortBindings_Protocol.
var (
	PortBindings_Protocol_name = map[int32]string{
		0: "unknown",
		1: "tcp",
		2: "udp",
	}
	PortBindings_Protocol_value = map[string]int32{
		"unknown": 0,
		"tcp":     1,
		"udp":     2,
	}
)

func (x PortBindings_Protocol) Enum() *PortBindings_Protocol {
	p := new(PortBindings_Protocol)
	*p = x
	return p
}

func (x PortBindings_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PortBindings_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_velez_api_proto_enumTypes[0].Descriptor()
}

func (PortBindings_Protocol) Type() protoreflect.EnumType {
	return &file_grpc_velez_api_proto_enumTypes[0]
}

func (x PortBindings_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PortBindings_Protocol.Descriptor instead.
func (PortBindings_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{1, 0}
}

type Smerd_Status int32

const (
	Smerd_unknown    Smerd_Status = 0
	Smerd_created    Smerd_Status = 1
	Smerd_restarting Smerd_Status = 2
	Smerd_running    Smerd_Status = 3
	Smerd_removing   Smerd_Status = 4
	Smerd_paused     Smerd_Status = 5
	Smerd_exited     Smerd_Status = 6
	Smerd_dead       Smerd_Status = 7
)

// Enum value maps for Smerd_Status.
var (
	Smerd_Status_name = map[int32]string{
		0: "unknown",
		1: "created",
		2: "restarting",
		3: "running",
		4: "removing",
		5: "paused",
		6: "exited",
		7: "dead",
	}
	Smerd_Status_value = map[string]int32{
		"unknown":    0,
		"created":    1,
		"restarting": 2,
		"running":    3,
		"removing":   4,
		"paused":     5,
		"exited":     6,
		"dead":       7,
	}
)

func (x Smerd_Status) Enum() *Smerd_Status {
	p := new(Smerd_Status)
	*p = x
	return p
}

func (x Smerd_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Smerd_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_velez_api_proto_enumTypes[1].Descriptor()
}

func (Smerd_Status) Type() protoreflect.EnumType {
	return &file_grpc_velez_api_proto_enumTypes[1]
}

func (x Smerd_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Smerd_Status.Descriptor instead.
func (Smerd_Status) EnumDescriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{4, 0}
}

type Version struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Version) Reset() {
	*x = Version{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{0}
}

type PortBindings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host      uint32                `protobuf:"varint,1,opt,name=host,proto3" json:"host,omitempty"`
	Container uint32                `protobuf:"varint,2,opt,name=container,proto3" json:"container,omitempty"`
	Protoc    PortBindings_Protocol `protobuf:"varint,3,opt,name=protoc,proto3,enum=velez_api.PortBindings_Protocol" json:"protoc,omitempty"`
}

func (x *PortBindings) Reset() {
	*x = PortBindings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PortBindings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortBindings) ProtoMessage() {}

func (x *PortBindings) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortBindings.ProtoReflect.Descriptor instead.
func (*PortBindings) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{1}
}

func (x *PortBindings) GetHost() uint32 {
	if x != nil {
		return x.Host
	}
	return 0
}

func (x *PortBindings) GetContainer() uint32 {
	if x != nil {
		return x.Container
	}
	return 0
}

func (x *PortBindings) GetProtoc() PortBindings_Protocol {
	if x != nil {
		return x.Protoc
	}
	return PortBindings_unknown
}

type VolumeBindings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host      string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Container string `protobuf:"bytes,2,opt,name=container,proto3" json:"container,omitempty"`
}

func (x *VolumeBindings) Reset() {
	*x = VolumeBindings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VolumeBindings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeBindings) ProtoMessage() {}

func (x *VolumeBindings) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeBindings.ProtoReflect.Descriptor instead.
func (*VolumeBindings) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{2}
}

func (x *VolumeBindings) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *VolumeBindings) GetContainer() string {
	if x != nil {
		return x.Container
	}
	return ""
}

type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tags []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{3}
}

func (x *Image) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Image) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Smerd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ImageName string                 `protobuf:"bytes,3,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Ports     []*PortBindings        `protobuf:"bytes,4,rep,name=ports,proto3" json:"ports,omitempty"`
	Volumes   []*VolumeBindings      `protobuf:"bytes,5,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Status    Smerd_Status           `protobuf:"varint,6,opt,name=status,proto3,enum=velez_api.Smerd_Status" json:"status,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Smerd) Reset() {
	*x = Smerd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Smerd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Smerd) ProtoMessage() {}

func (x *Smerd) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Smerd.ProtoReflect.Descriptor instead.
func (*Smerd) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{4}
}

func (x *Smerd) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Smerd) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Smerd) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *Smerd) GetPorts() []*PortBindings {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Smerd) GetVolumes() []*VolumeBindings {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *Smerd) GetStatus() Smerd_Status {
	if x != nil {
		return x.Status
	}
	return Smerd_unknown
}

func (x *Smerd) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Container struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Container) Reset() {
	*x = Container{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{5}
}

type CreateSmerd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateSmerd) Reset() {
	*x = CreateSmerd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSmerd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSmerd) ProtoMessage() {}

func (x *CreateSmerd) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSmerd.ProtoReflect.Descriptor instead.
func (*CreateSmerd) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{6}
}

type ListSmerds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListSmerds) Reset() {
	*x = ListSmerds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSmerds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSmerds) ProtoMessage() {}

func (x *ListSmerds) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSmerds.ProtoReflect.Descriptor instead.
func (*ListSmerds) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{7}
}

type DropSmerd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DropSmerd) Reset() {
	*x = DropSmerd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropSmerd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropSmerd) ProtoMessage() {}

func (x *DropSmerd) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropSmerd.ProtoReflect.Descriptor instead.
func (*DropSmerd) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{8}
}

type GetHardware struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHardware) Reset() {
	*x = GetHardware{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardware) ProtoMessage() {}

func (x *GetHardware) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardware.ProtoReflect.Descriptor instead.
func (*GetHardware) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{9}
}

type Version_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Version_Request) Reset() {
	*x = Version_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version_Request) ProtoMessage() {}

func (x *Version_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version_Request.ProtoReflect.Descriptor instead.
func (*Version_Request) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{0, 0}
}

type Version_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Version_Response) Reset() {
	*x = Version_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Version_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version_Response) ProtoMessage() {}

func (x *Version_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version_Response.ProtoReflect.Descriptor instead.
func (*Version_Response) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Version_Response) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Container_Hardware struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuAmount    *float32 `protobuf:"fixed32,1,opt,name=cpu_amount,json=cpuAmount,proto3,oneof" json:"cpu_amount,omitempty"`
	RamMb        *int32   `protobuf:"varint,2,opt,name=ram_mb,json=ramMb,proto3,oneof" json:"ram_mb,omitempty"`
	MemorySwapMb *int32   `protobuf:"varint,3,opt,name=memory_swap_mb,json=memorySwapMb,proto3,oneof" json:"memory_swap_mb,omitempty"`
}

func (x *Container_Hardware) Reset() {
	*x = Container_Hardware{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container_Hardware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container_Hardware) ProtoMessage() {}

func (x *Container_Hardware) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container_Hardware.ProtoReflect.Descriptor instead.
func (*Container_Hardware) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Container_Hardware) GetCpuAmount() float32 {
	if x != nil && x.CpuAmount != nil {
		return *x.CpuAmount
	}
	return 0
}

func (x *Container_Hardware) GetRamMb() int32 {
	if x != nil && x.RamMb != nil {
		return *x.RamMb
	}
	return 0
}

func (x *Container_Hardware) GetMemorySwapMb() int32 {
	if x != nil && x.MemorySwapMb != nil {
		return *x.MemorySwapMb
	}
	return 0
}

type Container_Settings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ports   []*PortBindings   `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	Volumes []*VolumeBindings `protobuf:"bytes,2,rep,name=volumes,proto3" json:"volumes,omitempty"`
}

func (x *Container_Settings) Reset() {
	*x = Container_Settings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Container_Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container_Settings) ProtoMessage() {}

func (x *Container_Settings) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container_Settings.ProtoReflect.Descriptor instead.
func (*Container_Settings) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Container_Settings) GetPorts() []*PortBindings {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *Container_Settings) GetVolumes() []*VolumeBindings {
	if x != nil {
		return x.Volumes
	}
	return nil
}

type CreateSmerd_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name            string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageName       string              `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Hardware        *Container_Hardware `protobuf:"bytes,3,opt,name=hardware,proto3,oneof" json:"hardware,omitempty"`
	Settings        *Container_Settings `protobuf:"bytes,4,opt,name=settings,proto3,oneof" json:"settings,omitempty"`
	AllowDuplicates bool                `protobuf:"varint,5,opt,name=allow_duplicates,json=allowDuplicates,proto3" json:"allow_duplicates,omitempty"`
	Command         *string             `protobuf:"bytes,6,opt,name=command,proto3,oneof" json:"command,omitempty"`
}

func (x *CreateSmerd_Request) Reset() {
	*x = CreateSmerd_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSmerd_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSmerd_Request) ProtoMessage() {}

func (x *CreateSmerd_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSmerd_Request.ProtoReflect.Descriptor instead.
func (*CreateSmerd_Request) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CreateSmerd_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSmerd_Request) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *CreateSmerd_Request) GetHardware() *Container_Hardware {
	if x != nil {
		return x.Hardware
	}
	return nil
}

func (x *CreateSmerd_Request) GetSettings() *Container_Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *CreateSmerd_Request) GetAllowDuplicates() bool {
	if x != nil {
		return x.AllowDuplicates
	}
	return false
}

func (x *CreateSmerd_Request) GetCommand() string {
	if x != nil && x.Command != nil {
		return *x.Command
	}
	return ""
}

type ListSmerds_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit *uint32 `protobuf:"varint,1,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
}

func (x *ListSmerds_Request) Reset() {
	*x = ListSmerds_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSmerds_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSmerds_Request) ProtoMessage() {}

func (x *ListSmerds_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSmerds_Request.ProtoReflect.Descriptor instead.
func (*ListSmerds_Request) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListSmerds_Request) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type ListSmerds_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Smerds []*Smerd `protobuf:"bytes,1,rep,name=smerds,proto3" json:"smerds,omitempty"`
}

func (x *ListSmerds_Response) Reset() {
	*x = ListSmerds_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSmerds_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSmerds_Response) ProtoMessage() {}

func (x *ListSmerds_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSmerds_Response.ProtoReflect.Descriptor instead.
func (*ListSmerds_Response) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{7, 1}
}

func (x *ListSmerds_Response) GetSmerds() []*Smerd {
	if x != nil {
		return x.Smerds
	}
	return nil
}

type DropSmerd_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuids []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
}

func (x *DropSmerd_Request) Reset() {
	*x = DropSmerd_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropSmerd_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropSmerd_Request) ProtoMessage() {}

func (x *DropSmerd_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropSmerd_Request.ProtoReflect.Descriptor instead.
func (*DropSmerd_Request) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DropSmerd_Request) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

type DropSmerd_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Failed     []*DropSmerd_Response_Error `protobuf:"bytes,1,rep,name=failed,proto3" json:"failed,omitempty"`
	Successful []string                    `protobuf:"bytes,2,rep,name=successful,proto3" json:"successful,omitempty"`
}

func (x *DropSmerd_Response) Reset() {
	*x = DropSmerd_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropSmerd_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropSmerd_Response) ProtoMessage() {}

func (x *DropSmerd_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropSmerd_Response.ProtoReflect.Descriptor instead.
func (*DropSmerd_Response) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{8, 1}
}

func (x *DropSmerd_Response) GetFailed() []*DropSmerd_Response_Error {
	if x != nil {
		return x.Failed
	}
	return nil
}

func (x *DropSmerd_Response) GetSuccessful() []string {
	if x != nil {
		return x.Successful
	}
	return nil
}

type DropSmerd_Response_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Cause string `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
}

func (x *DropSmerd_Response_Error) Reset() {
	*x = DropSmerd_Response_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DropSmerd_Response_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropSmerd_Response_Error) ProtoMessage() {}

func (x *DropSmerd_Response_Error) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropSmerd_Response_Error.ProtoReflect.Descriptor instead.
func (*DropSmerd_Response_Error) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{8, 1, 0}
}

func (x *DropSmerd_Response_Error) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *DropSmerd_Response_Error) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type GetHardware_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetHardware_Request) Reset() {
	*x = GetHardware_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHardware_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardware_Request) ProtoMessage() {}

func (x *GetHardware_Request) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardware_Request.ProtoReflect.Descriptor instead.
func (*GetHardware_Request) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{9, 0}
}

type GetHardware_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cpu            *GetHardware_Response_Value `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	DiskMem        *GetHardware_Response_Value `protobuf:"bytes,2,opt,name=disk_mem,json=diskMem,proto3" json:"disk_mem,omitempty"`
	Ram            *GetHardware_Response_Value `protobuf:"bytes,3,opt,name=ram,proto3" json:"ram,omitempty"`
	PortsAvailable []uint32                    `protobuf:"varint,4,rep,packed,name=ports_available,json=portsAvailable,proto3" json:"ports_available,omitempty"`
	PortsOccupied  []uint32                    `protobuf:"varint,5,rep,packed,name=ports_occupied,json=portsOccupied,proto3" json:"ports_occupied,omitempty"`
}

func (x *GetHardware_Response) Reset() {
	*x = GetHardware_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHardware_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardware_Response) ProtoMessage() {}

func (x *GetHardware_Response) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardware_Response.ProtoReflect.Descriptor instead.
func (*GetHardware_Response) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{9, 1}
}

func (x *GetHardware_Response) GetCpu() *GetHardware_Response_Value {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *GetHardware_Response) GetDiskMem() *GetHardware_Response_Value {
	if x != nil {
		return x.DiskMem
	}
	return nil
}

func (x *GetHardware_Response) GetRam() *GetHardware_Response_Value {
	if x != nil {
		return x.Ram
	}
	return nil
}

func (x *GetHardware_Response) GetPortsAvailable() []uint32 {
	if x != nil {
		return x.PortsAvailable
	}
	return nil
}

func (x *GetHardware_Response) GetPortsOccupied() []uint32 {
	if x != nil {
		return x.PortsOccupied
	}
	return nil
}

type GetHardware_Response_Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Err   string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetHardware_Response_Value) Reset() {
	*x = GetHardware_Response_Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_grpc_velez_api_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetHardware_Response_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHardware_Response_Value) ProtoMessage() {}

func (x *GetHardware_Response_Value) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_velez_api_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHardware_Response_Value.ProtoReflect.Descriptor instead.
func (*GetHardware_Response_Value) Descriptor() ([]byte, []int) {
	return file_grpc_velez_api_proto_rawDescGZIP(), []int{9, 1, 0}
}

func (x *GetHardware_Response_Value) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetHardware_Response_Value) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_grpc_velez_api_proto protoreflect.FileDescriptor

var file_grpc_velez_api_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70,
	0x69, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x1a, 0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xa5, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x72, 0x74, 0x42, 0x69,
	0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a,
	0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x6f, 0x72, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67,
	0x73, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x52, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x22, 0x29, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x0b,
	0x0a, 0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x74,
	0x63, 0x70, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x75, 0x64, 0x70, 0x10, 0x02, 0x22, 0x42, 0x0a,
	0x0e, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x22, 0x2f, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x74, 0x61,
	0x67, 0x73, 0x22, 0x8f, 0x03, 0x0a, 0x05, 0x53, 0x6d, 0x65, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x6f, 0x72, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x05, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x07,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f,
	0x61, 0x70, 0x69, 0x2e, 0x53, 0x6d, 0x65, 0x72, 0x64, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x6f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a,
	0x07, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x72, 0x65, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x75, 0x6e, 0x6e, 0x69,
	0x6e, 0x67, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x69, 0x6e, 0x67,
	0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x70, 0x61, 0x75, 0x73, 0x65, 0x64, 0x10, 0x05, 0x12, 0x0a,
	0x0a, 0x06, 0x65, 0x78, 0x69, 0x74, 0x65, 0x64, 0x10, 0x06, 0x12, 0x08, 0x0a, 0x04, 0x64, 0x65,
	0x61, 0x64, 0x10, 0x07, 0x22, 0xa0, 0x02, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e,
	0x65, 0x72, 0x1a, 0xa2, 0x01, 0x0a, 0x08, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x12,
	0x22, 0x0a, 0x0a, 0x63, 0x70, 0x75, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x02, 0x48, 0x00, 0x52, 0x09, 0x63, 0x70, 0x75, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x06, 0x72, 0x61, 0x6d, 0x5f, 0x6d, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x48, 0x01, 0x52, 0x05, 0x72, 0x61, 0x6d, 0x4d, 0x62, 0x88, 0x01, 0x01, 0x12,
	0x29, 0x0a, 0x0e, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x73, 0x77, 0x61, 0x70, 0x5f, 0x6d,
	0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x02, 0x52, 0x0c, 0x6d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x53, 0x77, 0x61, 0x70, 0x4d, 0x62, 0x88, 0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x63,
	0x70, 0x75, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x72, 0x61,
	0x6d, 0x5f, 0x6d, 0x62, 0x42, 0x11, 0x0a, 0x0f, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f,
	0x73, 0x77, 0x61, 0x70, 0x5f, 0x6d, 0x62, 0x1a, 0x6e, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x2d, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x50,
	0x6f, 0x72, 0x74, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x05, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x12, 0x33, 0x0a, 0x07, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x52, 0x07,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x73, 0x22, 0xe5, 0x02, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x6d, 0x65, 0x72, 0x64, 0x1a, 0xd5, 0x02, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x46, 0x0a, 0x0a, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x27, 0xfa, 0x42, 0x24,
	0x72, 0x22, 0x28, 0x32, 0x32, 0x1e, 0x28, 0x5b, 0x61, 0x2d, 0x7a, 0x5d, 0x2b, 0x29, 0x2f, 0x28,
	0x5b, 0x61, 0x2d, 0x7a, 0x5d, 0x2b, 0x29, 0x3a, 0x28, 0x5b, 0x61, 0x2d, 0x7a, 0x30, 0x2d, 0x39,
	0x2e, 0x5d, 0x2b, 0x29, 0x52, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x3e, 0x0a, 0x08, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65,
	0x48, 0x00, 0x52, 0x08, 0x68, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x88, 0x01, 0x01, 0x12,
	0x3e, 0x0a, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x48, 0x01, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x88, 0x01, 0x01, 0x12,
	0x29, 0x0a, 0x10, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x5f, 0x64, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x61, 0x6c, 0x6c, 0x6f, 0x77,
	0x44, 0x75, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x68, 0x61,
	0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22,
	0x72, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x65, 0x72, 0x64, 0x73, 0x1a, 0x2e, 0x0a,
	0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x1a, 0x34, 0x0a,
	0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x6d, 0x65,
	0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x76, 0x65, 0x6c, 0x65,
	0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6d, 0x65, 0x72, 0x64, 0x52, 0x06, 0x73, 0x6d, 0x65,
	0x72, 0x64, 0x73, 0x22, 0xc9, 0x01, 0x0a, 0x09, 0x44, 0x72, 0x6f, 0x70, 0x53, 0x6d, 0x65, 0x72,
	0x64, 0x1a, 0x1f, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x75, 0x75, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x75, 0x75, 0x69,
	0x64, 0x73, 0x1a, 0x9a, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x72, 0x6f, 0x70,
	0x53, 0x6d, 0x65, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x0a, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x1a, 0x31, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x75,
	0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x22,
	0xda, 0x02, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x1a,
	0x09, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0xbf, 0x02, 0x0a, 0x08, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x03, 0x63, 0x70, 0x75, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x47, 0x65, 0x74, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x63, 0x70, 0x75,
	0x12, 0x40, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x6b, 0x5f, 0x6d, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x74, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x07, 0x64, 0x69, 0x73, 0x6b, 0x4d,
	0x65, 0x6d, 0x12, 0x37, 0x0a, 0x03, 0x72, 0x61, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x25, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x48,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x03, 0x72, 0x61, 0x6d, 0x12, 0x27, 0x0a, 0x0f, 0x70,
	0x6f, 0x72, 0x74, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0d, 0x52, 0x0e, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x6f, 0x63,
	0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0d, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x4f, 0x63, 0x63, 0x75, 0x70, 0x69, 0x65, 0x64, 0x1a, 0x2f, 0x0a, 0x05, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0xe8, 0x03, 0x0a,
	0x08, 0x56, 0x65, 0x6c, 0x65, 0x7a, 0x41, 0x50, 0x49, 0x12, 0x57, 0x0a, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69,
	0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1b, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x3a, 0x01, 0x2a, 0x22, 0x08, 0x2f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x59, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x6d, 0x65, 0x72,
	0x64, 0x12, 0x1e, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x6d, 0x65, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6d,
	0x65, 0x72, 0x64, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x3a, 0x01, 0x2a, 0x22, 0x0d,
	0x2f, 0x73, 0x6d, 0x65, 0x72, 0x64, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x63, 0x0a,
	0x0a, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x65, 0x72, 0x64, 0x73, 0x12, 0x1d, 0x2e, 0x76, 0x65,
	0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x65, 0x72,
	0x64, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x65, 0x6c,
	0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x6d, 0x65, 0x72, 0x64,
	0x73, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x10, 0x3a, 0x01, 0x2a, 0x22, 0x0b, 0x2f, 0x73, 0x6d, 0x65, 0x72, 0x64, 0x2f, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x60, 0x0a, 0x09, 0x44, 0x72, 0x6f, 0x70, 0x53, 0x6d, 0x65, 0x72, 0x64, 0x12,
	0x1c, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x72, 0x6f, 0x70,
	0x53, 0x6d, 0x65, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e,
	0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x72, 0x6f, 0x70, 0x53, 0x6d,
	0x65, 0x72, 0x64, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x10, 0x3a, 0x01, 0x2a, 0x22, 0x0b, 0x2f, 0x73, 0x6d, 0x65, 0x72, 0x64, 0x2f,
	0x64, 0x72, 0x6f, 0x70, 0x12, 0x61, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x48, 0x61, 0x72, 0x64, 0x77,
	0x61, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x76, 0x65, 0x6c, 0x65, 0x7a, 0x5f, 0x61, 0x70, 0x69, 0x2e,
	0x47, 0x65, 0x74, 0x48, 0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x12, 0x09, 0x2f, 0x68,
	0x61, 0x72, 0x64, 0x77, 0x61, 0x72, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2f, 0x76, 0x65, 0x6c, 0x65,
	0x7a, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_grpc_velez_api_proto_rawDescOnce sync.Once
	file_grpc_velez_api_proto_rawDescData = file_grpc_velez_api_proto_rawDesc
)

func file_grpc_velez_api_proto_rawDescGZIP() []byte {
	file_grpc_velez_api_proto_rawDescOnce.Do(func() {
		file_grpc_velez_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_grpc_velez_api_proto_rawDescData)
	})
	return file_grpc_velez_api_proto_rawDescData
}

var file_grpc_velez_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_velez_api_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_grpc_velez_api_proto_goTypes = []interface{}{
	(PortBindings_Protocol)(0),         // 0: velez_api.PortBindings.Protocol
	(Smerd_Status)(0),                  // 1: velez_api.Smerd.Status
	(*Version)(nil),                    // 2: velez_api.Version
	(*PortBindings)(nil),               // 3: velez_api.PortBindings
	(*VolumeBindings)(nil),             // 4: velez_api.VolumeBindings
	(*Image)(nil),                      // 5: velez_api.Image
	(*Smerd)(nil),                      // 6: velez_api.Smerd
	(*Container)(nil),                  // 7: velez_api.Container
	(*CreateSmerd)(nil),                // 8: velez_api.CreateSmerd
	(*ListSmerds)(nil),                 // 9: velez_api.ListSmerds
	(*DropSmerd)(nil),                  // 10: velez_api.DropSmerd
	(*GetHardware)(nil),                // 11: velez_api.GetHardware
	(*Version_Request)(nil),            // 12: velez_api.Version.Request
	(*Version_Response)(nil),           // 13: velez_api.Version.Response
	(*Container_Hardware)(nil),         // 14: velez_api.Container.Hardware
	(*Container_Settings)(nil),         // 15: velez_api.Container.Settings
	(*CreateSmerd_Request)(nil),        // 16: velez_api.CreateSmerd.Request
	(*ListSmerds_Request)(nil),         // 17: velez_api.ListSmerds.Request
	(*ListSmerds_Response)(nil),        // 18: velez_api.ListSmerds.Response
	(*DropSmerd_Request)(nil),          // 19: velez_api.DropSmerd.Request
	(*DropSmerd_Response)(nil),         // 20: velez_api.DropSmerd.Response
	(*DropSmerd_Response_Error)(nil),   // 21: velez_api.DropSmerd.Response.Error
	(*GetHardware_Request)(nil),        // 22: velez_api.GetHardware.Request
	(*GetHardware_Response)(nil),       // 23: velez_api.GetHardware.Response
	(*GetHardware_Response_Value)(nil), // 24: velez_api.GetHardware.Response.Value
	(*timestamppb.Timestamp)(nil),      // 25: google.protobuf.Timestamp
}
var file_grpc_velez_api_proto_depIdxs = []int32{
	0,  // 0: velez_api.PortBindings.protoc:type_name -> velez_api.PortBindings.Protocol
	3,  // 1: velez_api.Smerd.ports:type_name -> velez_api.PortBindings
	4,  // 2: velez_api.Smerd.volumes:type_name -> velez_api.VolumeBindings
	1,  // 3: velez_api.Smerd.status:type_name -> velez_api.Smerd.Status
	25, // 4: velez_api.Smerd.created_at:type_name -> google.protobuf.Timestamp
	3,  // 5: velez_api.Container.Settings.ports:type_name -> velez_api.PortBindings
	4,  // 6: velez_api.Container.Settings.volumes:type_name -> velez_api.VolumeBindings
	14, // 7: velez_api.CreateSmerd.Request.hardware:type_name -> velez_api.Container.Hardware
	15, // 8: velez_api.CreateSmerd.Request.settings:type_name -> velez_api.Container.Settings
	6,  // 9: velez_api.ListSmerds.Response.smerds:type_name -> velez_api.Smerd
	21, // 10: velez_api.DropSmerd.Response.failed:type_name -> velez_api.DropSmerd.Response.Error
	24, // 11: velez_api.GetHardware.Response.cpu:type_name -> velez_api.GetHardware.Response.Value
	24, // 12: velez_api.GetHardware.Response.disk_mem:type_name -> velez_api.GetHardware.Response.Value
	24, // 13: velez_api.GetHardware.Response.ram:type_name -> velez_api.GetHardware.Response.Value
	12, // 14: velez_api.VelezAPI.Version:input_type -> velez_api.Version.Request
	16, // 15: velez_api.VelezAPI.CreateSmerd:input_type -> velez_api.CreateSmerd.Request
	17, // 16: velez_api.VelezAPI.ListSmerds:input_type -> velez_api.ListSmerds.Request
	19, // 17: velez_api.VelezAPI.DropSmerd:input_type -> velez_api.DropSmerd.Request
	22, // 18: velez_api.VelezAPI.GetHardware:input_type -> velez_api.GetHardware.Request
	13, // 19: velez_api.VelezAPI.Version:output_type -> velez_api.Version.Response
	6,  // 20: velez_api.VelezAPI.CreateSmerd:output_type -> velez_api.Smerd
	18, // 21: velez_api.VelezAPI.ListSmerds:output_type -> velez_api.ListSmerds.Response
	20, // 22: velez_api.VelezAPI.DropSmerd:output_type -> velez_api.DropSmerd.Response
	23, // 23: velez_api.VelezAPI.GetHardware:output_type -> velez_api.GetHardware.Response
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_grpc_velez_api_proto_init() }
func file_grpc_velez_api_proto_init() {
	if File_grpc_velez_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_grpc_velez_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PortBindings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VolumeBindings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Smerd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSmerd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSmerds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropSmerd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHardware); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Version_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container_Hardware); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Container_Settings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSmerd_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSmerds_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListSmerds_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropSmerd_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropSmerd_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DropSmerd_Response_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHardware_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHardware_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_grpc_velez_api_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetHardware_Response_Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_grpc_velez_api_proto_msgTypes[12].OneofWrappers = []interface{}{}
	file_grpc_velez_api_proto_msgTypes[14].OneofWrappers = []interface{}{}
	file_grpc_velez_api_proto_msgTypes[15].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_grpc_velez_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_velez_api_proto_goTypes,
		DependencyIndexes: file_grpc_velez_api_proto_depIdxs,
		EnumInfos:         file_grpc_velez_api_proto_enumTypes,
		MessageInfos:      file_grpc_velez_api_proto_msgTypes,
	}.Build()
	File_grpc_velez_api_proto = out.File
	file_grpc_velez_api_proto_rawDesc = nil
	file_grpc_velez_api_proto_goTypes = nil
	file_grpc_velez_api_proto_depIdxs = nil
}
