// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.3
// source: verv_closed_network.proto

package velez_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VcnApi_CreateNamespace_FullMethodName = "/velez_api.VcnApi/CreateNamespace"
	VcnApi_ListNamespaces_FullMethodName  = "/velez_api.VcnApi/ListNamespaces"
	VcnApi_ConnectService_FullMethodName  = "/velez_api.VcnApi/ConnectService"
	VcnApi_ConnectUser_FullMethodName     = "/velez_api.VcnApi/ConnectUser"
	VcnApi_DeleteNamespace_FullMethodName = "/velez_api.VcnApi/DeleteNamespace"
)

// VcnApiClient is the client API for VcnApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Verv Closed Network
type VcnApiClient interface {
	CreateNamespace(ctx context.Context, in *CreateVcnNamespace_Request, opts ...grpc.CallOption) (*CreateVcnNamespace_Response, error)
	ListNamespaces(ctx context.Context, in *ListVcnNamespaces_Request, opts ...grpc.CallOption) (*ListVcnNamespaces_Response, error)
	ConnectService(ctx context.Context, in *ConnectService_Request, opts ...grpc.CallOption) (*ConnectService_Response, error)
	ConnectUser(ctx context.Context, in *ConnectUser_Request, opts ...grpc.CallOption) (*ConnectUser_Response, error)
	// Not implemented
	DeleteNamespace(ctx context.Context, in *DeleteVcnNamespace_Request, opts ...grpc.CallOption) (*DeleteVcnNamespace_Response, error)
}

type vcnApiClient struct {
	cc grpc.ClientConnInterface
}

func NewVcnApiClient(cc grpc.ClientConnInterface) VcnApiClient {
	return &vcnApiClient{cc}
}

func (c *vcnApiClient) CreateNamespace(ctx context.Context, in *CreateVcnNamespace_Request, opts ...grpc.CallOption) (*CreateVcnNamespace_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVcnNamespace_Response)
	err := c.cc.Invoke(ctx, VcnApi_CreateNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vcnApiClient) ListNamespaces(ctx context.Context, in *ListVcnNamespaces_Request, opts ...grpc.CallOption) (*ListVcnNamespaces_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVcnNamespaces_Response)
	err := c.cc.Invoke(ctx, VcnApi_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vcnApiClient) ConnectService(ctx context.Context, in *ConnectService_Request, opts ...grpc.CallOption) (*ConnectService_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectService_Response)
	err := c.cc.Invoke(ctx, VcnApi_ConnectService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vcnApiClient) ConnectUser(ctx context.Context, in *ConnectUser_Request, opts ...grpc.CallOption) (*ConnectUser_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectUser_Response)
	err := c.cc.Invoke(ctx, VcnApi_ConnectUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vcnApiClient) DeleteNamespace(ctx context.Context, in *DeleteVcnNamespace_Request, opts ...grpc.CallOption) (*DeleteVcnNamespace_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVcnNamespace_Response)
	err := c.cc.Invoke(ctx, VcnApi_DeleteNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VcnApiServer is the server API for VcnApi service.
// All implementations must embed UnimplementedVcnApiServer
// for forward compatibility.
//
// Verv Closed Network
type VcnApiServer interface {
	CreateNamespace(context.Context, *CreateVcnNamespace_Request) (*CreateVcnNamespace_Response, error)
	ListNamespaces(context.Context, *ListVcnNamespaces_Request) (*ListVcnNamespaces_Response, error)
	ConnectService(context.Context, *ConnectService_Request) (*ConnectService_Response, error)
	ConnectUser(context.Context, *ConnectUser_Request) (*ConnectUser_Response, error)
	// Not implemented
	DeleteNamespace(context.Context, *DeleteVcnNamespace_Request) (*DeleteVcnNamespace_Response, error)
	mustEmbedUnimplementedVcnApiServer()
}

// UnimplementedVcnApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVcnApiServer struct{}

func (UnimplementedVcnApiServer) CreateNamespace(context.Context, *CreateVcnNamespace_Request) (*CreateVcnNamespace_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNamespace not implemented")
}
func (UnimplementedVcnApiServer) ListNamespaces(context.Context, *ListVcnNamespaces_Request) (*ListVcnNamespaces_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedVcnApiServer) ConnectService(context.Context, *ConnectService_Request) (*ConnectService_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectService not implemented")
}
func (UnimplementedVcnApiServer) ConnectUser(context.Context, *ConnectUser_Request) (*ConnectUser_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectUser not implemented")
}
func (UnimplementedVcnApiServer) DeleteNamespace(context.Context, *DeleteVcnNamespace_Request) (*DeleteVcnNamespace_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNamespace not implemented")
}
func (UnimplementedVcnApiServer) mustEmbedUnimplementedVcnApiServer() {}
func (UnimplementedVcnApiServer) testEmbeddedByValue()                {}

// UnsafeVcnApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VcnApiServer will
// result in compilation errors.
type UnsafeVcnApiServer interface {
	mustEmbedUnimplementedVcnApiServer()
}

func RegisterVcnApiServer(s grpc.ServiceRegistrar, srv VcnApiServer) {
	// If the following call panics, it indicates UnimplementedVcnApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VcnApi_ServiceDesc, srv)
}

func _VcnApi_CreateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVcnNamespace_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VcnApiServer).CreateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VcnApi_CreateNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VcnApiServer).CreateNamespace(ctx, req.(*CreateVcnNamespace_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _VcnApi_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVcnNamespaces_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VcnApiServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VcnApi_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VcnApiServer).ListNamespaces(ctx, req.(*ListVcnNamespaces_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _VcnApi_ConnectService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectService_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VcnApiServer).ConnectService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VcnApi_ConnectService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VcnApiServer).ConnectService(ctx, req.(*ConnectService_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _VcnApi_ConnectUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectUser_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VcnApiServer).ConnectUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VcnApi_ConnectUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VcnApiServer).ConnectUser(ctx, req.(*ConnectUser_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _VcnApi_DeleteNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVcnNamespace_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VcnApiServer).DeleteNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VcnApi_DeleteNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VcnApiServer).DeleteNamespace(ctx, req.(*DeleteVcnNamespace_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// VcnApi_ServiceDesc is the grpc.ServiceDesc for VcnApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VcnApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "velez_api.VcnApi",
	HandlerType: (*VcnApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNamespace",
			Handler:    _VcnApi_CreateNamespace_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _VcnApi_ListNamespaces_Handler,
		},
		{
			MethodName: "ConnectService",
			Handler:    _VcnApi_ConnectService_Handler,
		},
		{
			MethodName: "ConnectUser",
			Handler:    _VcnApi_ConnectUser_Handler,
		},
		{
			MethodName: "DeleteNamespace",
			Handler:    _VcnApi_DeleteNamespace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verv_closed_network.proto",
}
