CREATE ROLE :nodeName WITH LOGIN PASSWORD :pwd;

GRANT USAGE ON SCHEMA velez TO :nodeName;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA velez TO :nodeName;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA velez TO :nodeName;

ALTER DEFAULT PRIVILEGES IN SCHEMA velez GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO :nodeName;
ALTER DEFAULT PRIVILEGES IN SCHEMA velez GRANT USAGE, SELECT ON SEQUENCES TO :nodeName;