### Get Version
POST {{velez}}/version
Content-Type: application/json

{}

### Create smerd
POST {{velez}}/smerd/create
Content-Type: application/json

{
  "name": "matreshka-2",
  "image_name": "godverv/matreshka-be:latest",
  "settings": {
    "ports": [
      {
        "container": 50051,
        "protoc": "tcp"
      },
      {
        "container": 50052,
        "protoc": "tcp"
      }
    ]
  }
}

### List smerds
POST {{velez}}/smerd/list
Content-Type: application/json

{
}


### Delete smerds
POST {{velez}}/smerd/drop
Content-Type: application/json

{
  "uuids": ["59b340777d32e62069003ea49c51a7cc8dbfc1a40a1aa6e88bdec66759899802"]
}

### Get hardware
GET {{velez}}/hardware
Content-Type: application/json

{
}