### Get Version
POST {{velez}}/version
Content-Type: application/json

{}

### Create container
POST {{velez}}/create_smerd
Content-Type: application/json

{
  "name": "velez",
  "image_name": "godverv/velez:v0.0.7",
  "settings": {
    "ports": [
      {
        "host": 8000,
        "container": 50051,
        "protoc": "tcp"
      },
      {
        "host": 8001,
        "container": 50052,
        "protoc": "tcp"
      }
    ],
    "volumes": [
      {
        "host": "/Users/alexbukov/Desktop/velez_key",
        "container": "/velez_key"
      }
    ]
  }
}