### Get Version
GET {{velez}}/version
Content-Type: application/json

{}

### Create standalone smerd (not-verv)
POST {{velez}}/smerd/create
Content-Type: application/json

{
  "name": "angie",
  "image_name": "docker.angie.software/angie:latest",
  "settings": {
    "ports": [
      {
        "service_port_number": 80,
        "protocol": "tcp"
      }
    ]
  }
}

### Create smerd with dependecy
POST {{velez}}/smerd/create
Content-Type: application/json

{
  "name": "redzino",
  "image_name": "redsockruf/redzino_bot:v0.0.2"
}


### List smerds
POST {{velez}}/smerd/list
Content-Type: application/json

{}

### Delete smerds
POST {{velez}}/smerd/drop
Content-Type: application/json

{
  "uuids": ["59b340777d32e62069003ea49c51a7cc8dbfc1a40a1aa6e88bdec66759899802"]
}

### Get hardware
GET {{velez}}/hardware
Content-Type: application/json

{}

### Fetch config
POST {{velez}}/config/assemble
Content-Type: application/json

{
  "image_name": "redsockruf/redzino_bot:v0.0.2",
  "service_name": "redzino"
}