### Create app smerd
POST {{velez}}/api/smerd/create
Content-Type: application/json

{
  "name": "redzino",
  "image_name": "redsockruf/redzino_bot:v0.0.6",
  "settings": {
    "network": [
      {
        "network_name": "redzino"
      }
    ]
  }
}