// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: control_plane_api.proto

package velez_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VervServiceType int32

const (
	VervServiceType_unknown_service_type VervServiceType = 0
	VervServiceType_matreshka            VervServiceType = 1
	VervServiceType_makosh               VervServiceType = 2
	VervServiceType_webserver            VervServiceType = 3
	VervServiceType_headscale            VervServiceType = 4
	VervServiceType_portainer            VervServiceType = 5
	VervServiceType_statefull_pg         VervServiceType = 6
)

// Enum value maps for VervServiceType.
var (
	VervServiceType_name = map[int32]string{
		0: "unknown_service_type",
		1: "matreshka",
		2: "makosh",
		3: "webserver",
		4: "headscale",
		5: "portainer",
		6: "statefull_pg",
	}
	VervServiceType_value = map[string]int32{
		"unknown_service_type": 0,
		"matreshka":            1,
		"makosh":               2,
		"webserver":            3,
		"headscale":            4,
		"portainer":            5,
		"statefull_pg":         6,
	}
)

func (x VervServiceType) Enum() *VervServiceType {
	p := new(VervServiceType)
	*p = x
	return p
}

func (x VervServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VervServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_control_plane_api_proto_enumTypes[0].Descriptor()
}

func (VervServiceType) Type() protoreflect.EnumType {
	return &file_control_plane_api_proto_enumTypes[0]
}

func (x VervServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VervServiceType.Descriptor instead.
func (VervServiceType) EnumDescriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{0}
}

type VervService_State int32

const (
	VervService_unknown  VervService_State = 0
	VervService_running  VervService_State = 1
	VervService_warning  VervService_State = 2
	VervService_dead     VervService_State = 3
	VervService_disabled VervService_State = 4
)

// Enum value maps for VervService_State.
var (
	VervService_State_name = map[int32]string{
		0: "unknown",
		1: "running",
		2: "warning",
		3: "dead",
		4: "disabled",
	}
	VervService_State_value = map[string]int32{
		"unknown":  0,
		"running":  1,
		"warning":  2,
		"dead":     3,
		"disabled": 4,
	}
)

func (x VervService_State) Enum() *VervService_State {
	p := new(VervService_State)
	*p = x
	return p
}

func (x VervService_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VervService_State) Descriptor() protoreflect.EnumDescriptor {
	return file_control_plane_api_proto_enumTypes[1].Descriptor()
}

func (VervService_State) Type() protoreflect.EnumType {
	return &file_control_plane_api_proto_enumTypes[1]
}

func (x VervService_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VervService_State.Descriptor instead.
func (VervService_State) EnumDescriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{1, 0}
}

type ListVervServices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVervServices) Reset() {
	*x = ListVervServices{}
	mi := &file_control_plane_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVervServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVervServices) ProtoMessage() {}

func (x *ListVervServices) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVervServices.ProtoReflect.Descriptor instead.
func (*ListVervServices) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{0}
}

type VervService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          VervServiceType        `protobuf:"varint,1,opt,name=type,proto3,enum=velez_api.VervServiceType" json:"type,omitempty"`
	Port          *uint32                `protobuf:"varint,2,opt,name=port,proto3,oneof" json:"port,omitempty"`
	State         VervService_State      `protobuf:"varint,3,opt,name=state,proto3,enum=velez_api.VervService_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VervService) Reset() {
	*x = VervService{}
	mi := &file_control_plane_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VervService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VervService) ProtoMessage() {}

func (x *VervService) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VervService.ProtoReflect.Descriptor instead.
func (*VervService) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{1}
}

func (x *VervService) GetType() VervServiceType {
	if x != nil {
		return x.Type
	}
	return VervServiceType_unknown_service_type
}

func (x *VervService) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *VervService) GetState() VervService_State {
	if x != nil {
		return x.State
	}
	return VervService_unknown
}

type EnableService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableService) Reset() {
	*x = EnableService{}
	mi := &file_control_plane_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableService) ProtoMessage() {}

func (x *EnableService) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableService.ProtoReflect.Descriptor instead.
func (*EnableService) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{2}
}

type InitMaster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitMaster) Reset() {
	*x = InitMaster{}
	mi := &file_control_plane_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitMaster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMaster) ProtoMessage() {}

func (x *InitMaster) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMaster.ProtoReflect.Descriptor instead.
func (*InitMaster) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{3}
}

type ConnectSlave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSlave) Reset() {
	*x = ConnectSlave{}
	mi := &file_control_plane_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSlave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSlave) ProtoMessage() {}

func (x *ConnectSlave) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSlave.ProtoReflect.Descriptor instead.
func (*ConnectSlave) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{4}
}

type EnableStatefullCluster struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsExposePort  *bool                  `protobuf:"varint,1,opt,name=is_expose_port,json=isExposePort,proto3,oneof" json:"is_expose_port,omitempty"`
	ExposeToPort  *uint64                `protobuf:"varint,2,opt,name=expose_to_port,json=exposeToPort,proto3,oneof" json:"expose_to_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableStatefullCluster) Reset() {
	*x = EnableStatefullCluster{}
	mi := &file_control_plane_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableStatefullCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableStatefullCluster) ProtoMessage() {}

func (x *EnableStatefullCluster) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableStatefullCluster.ProtoReflect.Descriptor instead.
func (*EnableStatefullCluster) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{5}
}

func (x *EnableStatefullCluster) GetIsExposePort() bool {
	if x != nil && x.IsExposePort != nil {
		return *x.IsExposePort
	}
	return false
}

func (x *EnableStatefullCluster) GetExposeToPort() uint64 {
	if x != nil && x.ExposeToPort != nil {
		return *x.ExposeToPort
	}
	return 0
}

type EnableHeadscaleServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EnableHeadscaleServer_DeployConfig
	//	*EnableHeadscaleServer_ExternalConnect
	Payload       isEnableHeadscaleServer_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableHeadscaleServer) Reset() {
	*x = EnableHeadscaleServer{}
	mi := &file_control_plane_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableHeadscaleServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableHeadscaleServer) ProtoMessage() {}

func (x *EnableHeadscaleServer) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableHeadscaleServer.ProtoReflect.Descriptor instead.
func (*EnableHeadscaleServer) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{6}
}

func (x *EnableHeadscaleServer) GetPayload() isEnableHeadscaleServer_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnableHeadscaleServer) GetDeployConfig() *EnableHeadscaleServer_DeployHeadscaleConfig {
	if x != nil {
		if x, ok := x.Payload.(*EnableHeadscaleServer_DeployConfig); ok {
			return x.DeployConfig
		}
	}
	return nil
}

func (x *EnableHeadscaleServer) GetExternalConnect() *EnableHeadscaleServer_ExternalHeadscaleConnection {
	if x != nil {
		if x, ok := x.Payload.(*EnableHeadscaleServer_ExternalConnect); ok {
			return x.ExternalConnect
		}
	}
	return nil
}

type isEnableHeadscaleServer_Payload interface {
	isEnableHeadscaleServer_Payload()
}

type EnableHeadscaleServer_DeployConfig struct {
	DeployConfig *EnableHeadscaleServer_DeployHeadscaleConfig `protobuf:"bytes,1,opt,name=deploy_config,json=deployConfig,proto3,oneof"`
}

type EnableHeadscaleServer_ExternalConnect struct {
	ExternalConnect *EnableHeadscaleServer_ExternalHeadscaleConnection `protobuf:"bytes,2,opt,name=external_connect,json=externalConnect,proto3,oneof"`
}

func (*EnableHeadscaleServer_DeployConfig) isEnableHeadscaleServer_Payload() {}

func (*EnableHeadscaleServer_ExternalConnect) isEnableHeadscaleServer_Payload() {}

type ListNodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodes) Reset() {
	*x = ListNodes{}
	mi := &file_control_plane_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodes) ProtoMessage() {}

func (x *ListNodes) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodes.ProtoReflect.Descriptor instead.
func (*ListNodes) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{7}
}

type ListVervServices_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVervServices_Request) Reset() {
	*x = ListVervServices_Request{}
	mi := &file_control_plane_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVervServices_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVervServices_Request) ProtoMessage() {}

func (x *ListVervServices_Request) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVervServices_Request.ProtoReflect.Descriptor instead.
func (*ListVervServices_Request) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{0, 0}
}

type ListVervServices_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*VervService         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVervServices_Response) Reset() {
	*x = ListVervServices_Response{}
	mi := &file_control_plane_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVervServices_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVervServices_Response) ProtoMessage() {}

func (x *ListVervServices_Response) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVervServices_Response.ProtoReflect.Descriptor instead.
func (*ListVervServices_Response) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *ListVervServices_Response) GetServices() []*VervService {
	if x != nil {
		return x.Services
	}
	return nil
}

type EnableService_Request struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Service VervServiceType        `protobuf:"varint,1,opt,name=service,proto3,enum=velez_api.VervServiceType" json:"service,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EnableService_Request_StatefullCluster
	//	*EnableService_Request_HeadscaleServer
	Payload       isEnableService_Request_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableService_Request) Reset() {
	*x = EnableService_Request{}
	mi := &file_control_plane_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableService_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableService_Request) ProtoMessage() {}

func (x *EnableService_Request) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableService_Request.ProtoReflect.Descriptor instead.
func (*EnableService_Request) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *EnableService_Request) GetService() VervServiceType {
	if x != nil {
		return x.Service
	}
	return VervServiceType_unknown_service_type
}

func (x *EnableService_Request) GetPayload() isEnableService_Request_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnableService_Request) GetStatefullCluster() *EnableStatefullCluster {
	if x != nil {
		if x, ok := x.Payload.(*EnableService_Request_StatefullCluster); ok {
			return x.StatefullCluster
		}
	}
	return nil
}

func (x *EnableService_Request) GetHeadscaleServer() *EnableHeadscaleServer {
	if x != nil {
		if x, ok := x.Payload.(*EnableService_Request_HeadscaleServer); ok {
			return x.HeadscaleServer
		}
	}
	return nil
}

type isEnableService_Request_Payload interface {
	isEnableService_Request_Payload()
}

type EnableService_Request_StatefullCluster struct {
	StatefullCluster *EnableStatefullCluster `protobuf:"bytes,2,opt,name=statefull_cluster,json=statefullCluster,proto3,oneof"`
}

type EnableService_Request_HeadscaleServer struct {
	HeadscaleServer *EnableHeadscaleServer `protobuf:"bytes,3,opt,name=headscale_server,json=headscaleServer,proto3,oneof"`
}

func (*EnableService_Request_StatefullCluster) isEnableService_Request_Payload() {}

func (*EnableService_Request_HeadscaleServer) isEnableService_Request_Payload() {}

type EnableService_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableService_Response) Reset() {
	*x = EnableService_Response{}
	mi := &file_control_plane_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableService_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableService_Response) ProtoMessage() {}

func (x *EnableService_Response) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableService_Response.ProtoReflect.Descriptor instead.
func (*EnableService_Response) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{2, 1}
}

type InitMaster_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitMaster_Request) Reset() {
	*x = InitMaster_Request{}
	mi := &file_control_plane_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitMaster_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMaster_Request) ProtoMessage() {}

func (x *InitMaster_Request) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMaster_Request.ProtoReflect.Descriptor instead.
func (*InitMaster_Request) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{3, 0}
}

type InitMaster_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitMaster_Response) Reset() {
	*x = InitMaster_Response{}
	mi := &file_control_plane_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitMaster_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitMaster_Response) ProtoMessage() {}

func (x *InitMaster_Response) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitMaster_Response.ProtoReflect.Descriptor instead.
func (*InitMaster_Response) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{3, 1}
}

type ConnectSlave_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSlave_Request) Reset() {
	*x = ConnectSlave_Request{}
	mi := &file_control_plane_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSlave_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSlave_Request) ProtoMessage() {}

func (x *ConnectSlave_Request) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSlave_Request.ProtoReflect.Descriptor instead.
func (*ConnectSlave_Request) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{4, 0}
}

type ConnectSlave_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectSlave_Response) Reset() {
	*x = ConnectSlave_Response{}
	mi := &file_control_plane_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectSlave_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSlave_Response) ProtoMessage() {}

func (x *ConnectSlave_Response) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSlave_Response.ProtoReflect.Descriptor instead.
func (*ConnectSlave_Response) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{4, 1}
}

type EnableHeadscaleServer_ExternalHeadscaleConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableHeadscaleServer_ExternalHeadscaleConnection) Reset() {
	*x = EnableHeadscaleServer_ExternalHeadscaleConnection{}
	mi := &file_control_plane_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableHeadscaleServer_ExternalHeadscaleConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableHeadscaleServer_ExternalHeadscaleConnection) ProtoMessage() {}

func (x *EnableHeadscaleServer_ExternalHeadscaleConnection) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableHeadscaleServer_ExternalHeadscaleConnection.ProtoReflect.Descriptor instead.
func (*EnableHeadscaleServer_ExternalHeadscaleConnection) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *EnableHeadscaleServer_ExternalHeadscaleConnection) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EnableHeadscaleServer_ExternalHeadscaleConnection) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type EnableHeadscaleServer_DeployHeadscaleConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Headscale must export any port.
	// Using custom_port allows you to specify the port to expose to
	CustomPort *uint32 `protobuf:"varint,1,opt,name=custom_port,json=customPort,proto3,oneof" json:"custom_port,omitempty"`
	// Using custom_image you can specify the exact image to deploy
	CustomImage   *string `protobuf:"bytes,2,opt,name=custom_image,json=customImage,proto3,oneof" json:"custom_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableHeadscaleServer_DeployHeadscaleConfig) Reset() {
	*x = EnableHeadscaleServer_DeployHeadscaleConfig{}
	mi := &file_control_plane_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableHeadscaleServer_DeployHeadscaleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableHeadscaleServer_DeployHeadscaleConfig) ProtoMessage() {}

func (x *EnableHeadscaleServer_DeployHeadscaleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableHeadscaleServer_DeployHeadscaleConfig.ProtoReflect.Descriptor instead.
func (*EnableHeadscaleServer_DeployHeadscaleConfig) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{6, 1}
}

func (x *EnableHeadscaleServer_DeployHeadscaleConfig) GetCustomPort() uint32 {
	if x != nil && x.CustomPort != nil {
		return *x.CustomPort
	}
	return 0
}

func (x *EnableHeadscaleServer_DeployHeadscaleConfig) GetCustomImage() string {
	if x != nil && x.CustomImage != nil {
		return *x.CustomImage
	}
	return ""
}

type ListNodes_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *Paging                `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodes_Request) Reset() {
	*x = ListNodes_Request{}
	mi := &file_control_plane_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodes_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodes_Request) ProtoMessage() {}

func (x *ListNodes_Request) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodes_Request.ProtoReflect.Descriptor instead.
func (*ListNodes_Request) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListNodes_Request) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type ListNodes_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeBaseInfo        `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodes_Response) Reset() {
	*x = ListNodes_Response{}
	mi := &file_control_plane_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodes_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodes_Response) ProtoMessage() {}

func (x *ListNodes_Response) ProtoReflect() protoreflect.Message {
	mi := &file_control_plane_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodes_Response.ProtoReflect.Descriptor instead.
func (*ListNodes_Response) Descriptor() ([]byte, []int) {
	return file_control_plane_api_proto_rawDescGZIP(), []int{7, 1}
}

func (x *ListNodes_Response) GetNodes() []*NodeBaseInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodes_Response) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_control_plane_api_proto protoreflect.FileDescriptor

const file_control_plane_api_proto_rawDesc = "" +
	"\n" +
	"\x17control_plane_api.proto\x12\tvelez_api\x1a\x1cgoogle/api/annotations.proto\x1a\tnpm.proto\x1a\x0fvelez_api.proto\x1a\x12velez_common.proto\"]\n" +
	"\x10ListVervServices\x1a\t\n" +
	"\aRequest\x1a>\n" +
	"\bResponse\x122\n" +
	"\bservices\x18\x01 \x03(\v2\x16.velez_api.VervServiceR\bservices\"\xdb\x01\n" +
	"\vVervService\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.velez_api.VervServiceTypeR\x04type\x12\x17\n" +
	"\x04port\x18\x02 \x01(\rH\x00R\x04port\x88\x01\x01\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.velez_api.VervService.StateR\x05state\"F\n" +
	"\x05State\x12\v\n" +
	"\aunknown\x10\x00\x12\v\n" +
	"\arunning\x10\x01\x12\v\n" +
	"\awarning\x10\x02\x12\b\n" +
	"\x04dead\x10\x03\x12\f\n" +
	"\bdisabled\x10\x04B\a\n" +
	"\x05_port\"\x89\x02\n" +
	"\rEnableService\x1a\xeb\x01\n" +
	"\aRequest\x124\n" +
	"\aservice\x18\x01 \x01(\x0e2\x1a.velez_api.VervServiceTypeR\aservice\x12P\n" +
	"\x11statefull_cluster\x18\x02 \x01(\v2!.velez_api.EnableStatefullClusterH\x00R\x10statefullCluster\x12M\n" +
	"\x10headscale_server\x18\x03 \x01(\v2 .velez_api.EnableHeadscaleServerH\x00R\x0fheadscaleServerB\t\n" +
	"\apayload\x1a\n" +
	"\n" +
	"\bResponse\"#\n" +
	"\n" +
	"InitMaster\x1a\t\n" +
	"\aRequest\x1a\n" +
	"\n" +
	"\bResponse\"%\n" +
	"\fConnectSlave\x1a\t\n" +
	"\aRequest\x1a\n" +
	"\n" +
	"\bResponse\"\x94\x01\n" +
	"\x16EnableStatefullCluster\x12)\n" +
	"\x0eis_expose_port\x18\x01 \x01(\bH\x00R\fisExposePort\x88\x01\x01\x12)\n" +
	"\x0eexpose_to_port\x18\x02 \x01(\x04H\x01R\fexposeToPort\x88\x01\x01B\x11\n" +
	"\x0f_is_expose_portB\x11\n" +
	"\x0f_expose_to_port\"\xbc\x03\n" +
	"\x15EnableHeadscaleServer\x12]\n" +
	"\rdeploy_config\x18\x01 \x01(\v26.velez_api.EnableHeadscaleServer.DeployHeadscaleConfigH\x00R\fdeployConfig\x12i\n" +
	"\x10external_connect\x18\x02 \x01(\v2<.velez_api.EnableHeadscaleServer.ExternalHeadscaleConnectionH\x00R\x0fexternalConnect\x1aE\n" +
	"\x1bExternalHeadscaleConnection\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x1a\x86\x01\n" +
	"\x15DeployHeadscaleConfig\x12$\n" +
	"\vcustom_port\x18\x01 \x01(\rH\x00R\n" +
	"customPort\x88\x01\x01\x12&\n" +
	"\fcustom_image\x18\x02 \x01(\tH\x01R\vcustomImage\x88\x01\x01B\x0e\n" +
	"\f_custom_portB\x0f\n" +
	"\r_custom_imageB\t\n" +
	"\apayload\"\x92\x01\n" +
	"\tListNodes\x1a4\n" +
	"\aRequest\x12)\n" +
	"\x06paging\x18\x01 \x01(\v2\x11.velez_api.PagingR\x06paging\x1aO\n" +
	"\bResponse\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.velez_api.NodeBaseInfoR\x05nodes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total*\x85\x01\n" +
	"\x0fVervServiceType\x12\x18\n" +
	"\x14unknown_service_type\x10\x00\x12\r\n" +
	"\tmatreshka\x10\x01\x12\n" +
	"\n" +
	"\x06makosh\x10\x02\x12\r\n" +
	"\twebserver\x10\x03\x12\r\n" +
	"\theadscale\x10\x04\x12\r\n" +
	"\tportainer\x10\x05\x12\x10\n" +
	"\fstatefull_pg\x10\x062\x8f\x04\n" +
	"\x0fControlPlaneAPI\x12\x82\x01\n" +
	"\x10ListVervServices\x12#.velez_api.ListVervServices.Request\x1a$.velez_api.ListVervServices.Response\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/control_plane/services\x12\x82\x01\n" +
	"\rEnableService\x12 .velez_api.EnableService.Request\x1a!.velez_api.EnableService.Response\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/control_plane/service/enable\x12~\n" +
	"\fConnectSlave\x12\x1f.velez_api.ConnectSlave.Request\x1a .velez_api.ConnectSlave.Response\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/control_plane/slave/connect\x12r\n" +
	"\tListNodes\x12\x1c.velez_api.ListNodes.Request\x1a\x1d.velez_api.ListNodes.Response\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/control_plane/nodes/listBC\x92\x82\x19\x10@vervstack/velezZ-go.vervstack.ru/velez/pkg/velez_api;velez_apib\x06proto3"

var (
	file_control_plane_api_proto_rawDescOnce sync.Once
	file_control_plane_api_proto_rawDescData []byte
)

func file_control_plane_api_proto_rawDescGZIP() []byte {
	file_control_plane_api_proto_rawDescOnce.Do(func() {
		file_control_plane_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_plane_api_proto_rawDesc), len(file_control_plane_api_proto_rawDesc)))
	})
	return file_control_plane_api_proto_rawDescData
}

var file_control_plane_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_control_plane_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_control_plane_api_proto_goTypes = []any{
	(VervServiceType)(0),                                      // 0: velez_api.VervServiceType
	(VervService_State)(0),                                    // 1: velez_api.VervService.State
	(*ListVervServices)(nil),                                  // 2: velez_api.ListVervServices
	(*VervService)(nil),                                       // 3: velez_api.VervService
	(*EnableService)(nil),                                     // 4: velez_api.EnableService
	(*InitMaster)(nil),                                        // 5: velez_api.InitMaster
	(*ConnectSlave)(nil),                                      // 6: velez_api.ConnectSlave
	(*EnableStatefullCluster)(nil),                            // 7: velez_api.EnableStatefullCluster
	(*EnableHeadscaleServer)(nil),                             // 8: velez_api.EnableHeadscaleServer
	(*ListNodes)(nil),                                         // 9: velez_api.ListNodes
	(*ListVervServices_Request)(nil),                          // 10: velez_api.ListVervServices.Request
	(*ListVervServices_Response)(nil),                         // 11: velez_api.ListVervServices.Response
	(*EnableService_Request)(nil),                             // 12: velez_api.EnableService.Request
	(*EnableService_Response)(nil),                            // 13: velez_api.EnableService.Response
	(*InitMaster_Request)(nil),                                // 14: velez_api.InitMaster.Request
	(*InitMaster_Response)(nil),                               // 15: velez_api.InitMaster.Response
	(*ConnectSlave_Request)(nil),                              // 16: velez_api.ConnectSlave.Request
	(*ConnectSlave_Response)(nil),                             // 17: velez_api.ConnectSlave.Response
	(*EnableHeadscaleServer_ExternalHeadscaleConnection)(nil), // 18: velez_api.EnableHeadscaleServer.ExternalHeadscaleConnection
	(*EnableHeadscaleServer_DeployHeadscaleConfig)(nil),       // 19: velez_api.EnableHeadscaleServer.DeployHeadscaleConfig
	(*ListNodes_Request)(nil),                                 // 20: velez_api.ListNodes.Request
	(*ListNodes_Response)(nil),                                // 21: velez_api.ListNodes.Response
	(*Paging)(nil),                                            // 22: velez_api.Paging
	(*NodeBaseInfo)(nil),                                      // 23: velez_api.NodeBaseInfo
}
var file_control_plane_api_proto_depIdxs = []int32{
	0,  // 0: velez_api.VervService.type:type_name -> velez_api.VervServiceType
	1,  // 1: velez_api.VervService.state:type_name -> velez_api.VervService.State
	19, // 2: velez_api.EnableHeadscaleServer.deploy_config:type_name -> velez_api.EnableHeadscaleServer.DeployHeadscaleConfig
	18, // 3: velez_api.EnableHeadscaleServer.external_connect:type_name -> velez_api.EnableHeadscaleServer.ExternalHeadscaleConnection
	3,  // 4: velez_api.ListVervServices.Response.services:type_name -> velez_api.VervService
	0,  // 5: velez_api.EnableService.Request.service:type_name -> velez_api.VervServiceType
	7,  // 6: velez_api.EnableService.Request.statefull_cluster:type_name -> velez_api.EnableStatefullCluster
	8,  // 7: velez_api.EnableService.Request.headscale_server:type_name -> velez_api.EnableHeadscaleServer
	22, // 8: velez_api.ListNodes.Request.paging:type_name -> velez_api.Paging
	23, // 9: velez_api.ListNodes.Response.nodes:type_name -> velez_api.NodeBaseInfo
	10, // 10: velez_api.ControlPlaneAPI.ListVervServices:input_type -> velez_api.ListVervServices.Request
	12, // 11: velez_api.ControlPlaneAPI.EnableService:input_type -> velez_api.EnableService.Request
	16, // 12: velez_api.ControlPlaneAPI.ConnectSlave:input_type -> velez_api.ConnectSlave.Request
	20, // 13: velez_api.ControlPlaneAPI.ListNodes:input_type -> velez_api.ListNodes.Request
	11, // 14: velez_api.ControlPlaneAPI.ListVervServices:output_type -> velez_api.ListVervServices.Response
	13, // 15: velez_api.ControlPlaneAPI.EnableService:output_type -> velez_api.EnableService.Response
	17, // 16: velez_api.ControlPlaneAPI.ConnectSlave:output_type -> velez_api.ConnectSlave.Response
	21, // 17: velez_api.ControlPlaneAPI.ListNodes:output_type -> velez_api.ListNodes.Response
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_control_plane_api_proto_init() }
func file_control_plane_api_proto_init() {
	if File_control_plane_api_proto != nil {
		return
	}
	file_velez_api_proto_init()
	file_velez_common_proto_init()
	file_control_plane_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_control_plane_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_control_plane_api_proto_msgTypes[6].OneofWrappers = []any{
		(*EnableHeadscaleServer_DeployConfig)(nil),
		(*EnableHeadscaleServer_ExternalConnect)(nil),
	}
	file_control_plane_api_proto_msgTypes[10].OneofWrappers = []any{
		(*EnableService_Request_StatefullCluster)(nil),
		(*EnableService_Request_HeadscaleServer)(nil),
	}
	file_control_plane_api_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_plane_api_proto_rawDesc), len(file_control_plane_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_plane_api_proto_goTypes,
		DependencyIndexes: file_control_plane_api_proto_depIdxs,
		EnumInfos:         file_control_plane_api_proto_enumTypes,
		MessageInfos:      file_control_plane_api_proto_msgTypes,
	}.Build()
	File_control_plane_api_proto = out.File
	file_control_plane_api_proto_goTypes = nil
	file_control_plane_api_proto_depIdxs = nil
}
