// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: pgaas_api.proto

package velez_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PgInstanceIsolation - isolation mode for a PG instance. Only
// PG_INSTANCE_ISOLATION_SEPARATE_INSTANCE is provisionable today -
// PG_INSTANCE_ISOLATION_SHARED_POOL is surfaced disabled in the UI. See
// docs/features/pgaas_and_registry_plugin.md section 3, "Isolation".
type PgInstanceIsolation int32

const (
	PgInstanceIsolation_PG_INSTANCE_ISOLATION_UNSPECIFIED       PgInstanceIsolation = 0
	PgInstanceIsolation_PG_INSTANCE_ISOLATION_SEPARATE_INSTANCE PgInstanceIsolation = 1
	PgInstanceIsolation_PG_INSTANCE_ISOLATION_SHARED_POOL       PgInstanceIsolation = 2
)

// Enum value maps for PgInstanceIsolation.
var (
	PgInstanceIsolation_name = map[int32]string{
		0: "PG_INSTANCE_ISOLATION_UNSPECIFIED",
		1: "PG_INSTANCE_ISOLATION_SEPARATE_INSTANCE",
		2: "PG_INSTANCE_ISOLATION_SHARED_POOL",
	}
	PgInstanceIsolation_value = map[string]int32{
		"PG_INSTANCE_ISOLATION_UNSPECIFIED":       0,
		"PG_INSTANCE_ISOLATION_SEPARATE_INSTANCE": 1,
		"PG_INSTANCE_ISOLATION_SHARED_POOL":       2,
	}
)

func (x PgInstanceIsolation) Enum() *PgInstanceIsolation {
	p := new(PgInstanceIsolation)
	*p = x
	return p
}

func (x PgInstanceIsolation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PgInstanceIsolation) Descriptor() protoreflect.EnumDescriptor {
	return file_pgaas_api_proto_enumTypes[0].Descriptor()
}

func (PgInstanceIsolation) Type() protoreflect.EnumType {
	return &file_pgaas_api_proto_enumTypes[0]
}

func (x PgInstanceIsolation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PgInstanceIsolation.Descriptor instead.
func (PgInstanceIsolation) EnumDescriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{0}
}

// PgInstance never carries a password - status, environment, image,
// container id and deploy history live on the underlying service/deployment
// rows and are read via ListSmerds/VervServicesService, not duplicated here.
type PgInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DbName        string                 `protobuf:"bytes,2,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Environment   string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	OwnerService  *string                `protobuf:"bytes,7,opt,name=owner_service,json=ownerService,proto3,oneof" json:"owner_service,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PgInstance) Reset() {
	*x = PgInstance{}
	mi := &file_pgaas_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgInstance) ProtoMessage() {}

func (x *PgInstance) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgInstance.ProtoReflect.Descriptor instead.
func (*PgInstance) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{0}
}

func (x *PgInstance) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PgInstance) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *PgInstance) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PgInstance) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PgInstance) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *PgInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PgInstance) GetOwnerService() string {
	if x != nil && x.OwnerService != nil {
		return *x.OwnerService
	}
	return ""
}

func (x *PgInstance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PgInstance) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListPgInstances struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPgInstances) Reset() {
	*x = ListPgInstances{}
	mi := &file_pgaas_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPgInstances) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPgInstances) ProtoMessage() {}

func (x *ListPgInstances) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPgInstances.ProtoReflect.Descriptor instead.
func (*ListPgInstances) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{1}
}

type CreatePgInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePgInstance) Reset() {
	*x = CreatePgInstance{}
	mi := &file_pgaas_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePgInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePgInstance) ProtoMessage() {}

func (x *CreatePgInstance) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePgInstance.ProtoReflect.Descriptor instead.
func (*CreatePgInstance) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{2}
}

type DropPgInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropPgInstance) Reset() {
	*x = DropPgInstance{}
	mi := &file_pgaas_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropPgInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropPgInstance) ProtoMessage() {}

func (x *DropPgInstance) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropPgInstance.ProtoReflect.Descriptor instead.
func (*DropPgInstance) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{3}
}

// GetPgInstanceCredentials.Response is the only PostgresAPI message that
// ever carries a password.
type GetPgInstanceCredentials struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPgInstanceCredentials) Reset() {
	*x = GetPgInstanceCredentials{}
	mi := &file_pgaas_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPgInstanceCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPgInstanceCredentials) ProtoMessage() {}

func (x *GetPgInstanceCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPgInstanceCredentials.ProtoReflect.Descriptor instead.
func (*GetPgInstanceCredentials) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{4}
}

type ListPgInstances_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *Paging                `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPgInstances_Request) Reset() {
	*x = ListPgInstances_Request{}
	mi := &file_pgaas_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPgInstances_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPgInstances_Request) ProtoMessage() {}

func (x *ListPgInstances_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPgInstances_Request.ProtoReflect.Descriptor instead.
func (*ListPgInstances_Request) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListPgInstances_Request) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

type ListPgInstances_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*PgInstance          `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPgInstances_Response) Reset() {
	*x = ListPgInstances_Response{}
	mi := &file_pgaas_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPgInstances_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPgInstances_Response) ProtoMessage() {}

func (x *ListPgInstances_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPgInstances_Response.ProtoReflect.Descriptor instead.
func (*ListPgInstances_Response) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ListPgInstances_Response) GetInstances() []*PgInstance {
	if x != nil {
		return x.Instances
	}
	return nil
}

func (x *ListPgInstances_Response) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreatePgInstance_Request struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Name         string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Environment  *string                `protobuf:"bytes,2,opt,name=environment,proto3,oneof" json:"environment,omitempty"`
	Box          *string                `protobuf:"bytes,3,opt,name=box,proto3,oneof" json:"box,omitempty"`
	ExposeToPort *uint32                `protobuf:"varint,4,opt,name=expose_to_port,json=exposeToPort,proto3,oneof" json:"expose_to_port,omitempty"`
	// owner_service - when set, a velez.service_resources binding is
	// recorded (owner_service, name, "postgres") once the instance is
	// created.
	OwnerService  *string `protobuf:"bytes,5,opt,name=owner_service,json=ownerService,proto3,oneof" json:"owner_service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePgInstance_Request) Reset() {
	*x = CreatePgInstance_Request{}
	mi := &file_pgaas_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePgInstance_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePgInstance_Request) ProtoMessage() {}

func (x *CreatePgInstance_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePgInstance_Request.ProtoReflect.Descriptor instead.
func (*CreatePgInstance_Request) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{2, 0}
}

func (x *CreatePgInstance_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePgInstance_Request) GetEnvironment() string {
	if x != nil && x.Environment != nil {
		return *x.Environment
	}
	return ""
}

func (x *CreatePgInstance_Request) GetBox() string {
	if x != nil && x.Box != nil {
		return *x.Box
	}
	return ""
}

func (x *CreatePgInstance_Request) GetExposeToPort() uint32 {
	if x != nil && x.ExposeToPort != nil {
		return *x.ExposeToPort
	}
	return 0
}

func (x *CreatePgInstance_Request) GetOwnerService() string {
	if x != nil && x.OwnerService != nil {
		return *x.OwnerService
	}
	return ""
}

type CreatePgInstance_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *PgInstance            `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePgInstance_Response) Reset() {
	*x = CreatePgInstance_Response{}
	mi := &file_pgaas_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePgInstance_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePgInstance_Response) ProtoMessage() {}

func (x *CreatePgInstance_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePgInstance_Response.ProtoReflect.Descriptor instead.
func (*CreatePgInstance_Response) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{2, 1}
}

func (x *CreatePgInstance_Response) GetInstance() *PgInstance {
	if x != nil {
		return x.Instance
	}
	return nil
}

type DropPgInstance_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropPgInstance_Request) Reset() {
	*x = DropPgInstance_Request{}
	mi := &file_pgaas_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropPgInstance_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropPgInstance_Request) ProtoMessage() {}

func (x *DropPgInstance_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropPgInstance_Request.ProtoReflect.Descriptor instead.
func (*DropPgInstance_Request) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{3, 0}
}

func (x *DropPgInstance_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DropPgInstance_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropPgInstance_Response) Reset() {
	*x = DropPgInstance_Response{}
	mi := &file_pgaas_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropPgInstance_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropPgInstance_Response) ProtoMessage() {}

func (x *DropPgInstance_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropPgInstance_Response.ProtoReflect.Descriptor instead.
func (*DropPgInstance_Response) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{3, 1}
}

type GetPgInstanceCredentials_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPgInstanceCredentials_Request) Reset() {
	*x = GetPgInstanceCredentials_Request{}
	mi := &file_pgaas_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPgInstanceCredentials_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPgInstanceCredentials_Request) ProtoMessage() {}

func (x *GetPgInstanceCredentials_Request) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPgInstanceCredentials_Request.ProtoReflect.Descriptor instead.
func (*GetPgInstanceCredentials_Request) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetPgInstanceCredentials_Request) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPgInstanceCredentials_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DbName        string                 `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Dsn           string                 `protobuf:"bytes,4,opt,name=dsn,proto3" json:"dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPgInstanceCredentials_Response) Reset() {
	*x = GetPgInstanceCredentials_Response{}
	mi := &file_pgaas_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPgInstanceCredentials_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPgInstanceCredentials_Response) ProtoMessage() {}

func (x *GetPgInstanceCredentials_Response) ProtoReflect() protoreflect.Message {
	mi := &file_pgaas_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPgInstanceCredentials_Response.ProtoReflect.Descriptor instead.
func (*GetPgInstanceCredentials_Response) Descriptor() ([]byte, []int) {
	return file_pgaas_api_proto_rawDescGZIP(), []int{4, 1}
}

func (x *GetPgInstanceCredentials_Response) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

func (x *GetPgInstanceCredentials_Response) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetPgInstanceCredentials_Response) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetPgInstanceCredentials_Response) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

var File_pgaas_api_proto protoreflect.FileDescriptor

const file_pgaas_api_proto_rawDesc = "" +
	"\n" +
	"\x0fpgaas_api.proto\x12\tvelez_api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\tnpm.proto\x1a\x12velez_common.proto\"\xd5\x02\n" +
	"\n" +
	"PgInstance\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\adb_name\x18\x02 \x01(\tR\x06dbName\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12(\n" +
	"\rowner_service\x18\a \x01(\tH\x00R\fownerService\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x10\n" +
	"\x0e_owner_service\"\x9e\x01\n" +
	"\x0fListPgInstances\x1a4\n" +
	"\aRequest\x12)\n" +
	"\x06paging\x18\x01 \x01(\v2\x11.velez_api.PagingR\x06paging\x1aU\n" +
	"\bResponse\x123\n" +
	"\tinstances\x18\x01 \x03(\v2\x15.velez_api.PgInstanceR\tinstances\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\"\xc1\x02\n" +
	"\x10CreatePgInstance\x1a\xed\x01\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12%\n" +
	"\venvironment\x18\x02 \x01(\tH\x00R\venvironment\x88\x01\x01\x12\x15\n" +
	"\x03box\x18\x03 \x01(\tH\x01R\x03box\x88\x01\x01\x12)\n" +
	"\x0eexpose_to_port\x18\x04 \x01(\rH\x02R\fexposeToPort\x88\x01\x01\x12(\n" +
	"\rowner_service\x18\x05 \x01(\tH\x03R\fownerService\x88\x01\x01B\x0e\n" +
	"\f_environmentB\x06\n" +
	"\x04_boxB\x11\n" +
	"\x0f_expose_to_portB\x10\n" +
	"\x0e_owner_service\x1a=\n" +
	"\bResponse\x121\n" +
	"\binstance\x18\x01 \x01(\v2\x15.velez_api.PgInstanceR\binstance\";\n" +
	"\x0eDropPgInstance\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1a\n" +
	"\n" +
	"\bResponse\"\xa8\x01\n" +
	"\x18GetPgInstanceCredentials\x1a\x1d\n" +
	"\aRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x1am\n" +
	"\bResponse\x12\x17\n" +
	"\adb_name\x18\x01 \x01(\tR\x06dbName\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x10\n" +
	"\x03dsn\x18\x04 \x01(\tR\x03dsn*\x90\x01\n" +
	"\x13PgInstanceIsolation\x12%\n" +
	"!PG_INSTANCE_ISOLATION_UNSPECIFIED\x10\x00\x12+\n" +
	"'PG_INSTANCE_ISOLATION_SEPARATE_INSTANCE\x10\x01\x12%\n" +
	"!PG_INSTANCE_ISOLATION_SHARED_POOL\x10\x022\xa2\x04\n" +
	"\vPostgresAPI\x12y\n" +
	"\x0fListPgInstances\x12\".velez_api.ListPgInstances.Request\x1a#.velez_api.ListPgInstances.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/postgres/list\x12~\n" +
	"\x10CreatePgInstance\x12#.velez_api.CreatePgInstance.Request\x1a$.velez_api.CreatePgInstance.Response\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/postgres/create\x12v\n" +
	"\x0eDropPgInstance\x12!.velez_api.DropPgInstance.Request\x1a\".velez_api.DropPgInstance.Response\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/postgres/drop\x12\x9f\x01\n" +
	"\x18GetPgInstanceCredentials\x12+.velez_api.GetPgInstanceCredentials.Request\x1a,.velez_api.GetPgInstanceCredentials.Response\"(\x82\xd3\xe4\x93\x02\"\x12 /api/postgres/{name}/credentialsBC\x92\x82\x19\x10@vervstack/velezZ-go.vervstack.ru/velez/pkg/velez_api;velez_apib\x06proto3"

var (
	file_pgaas_api_proto_rawDescOnce sync.Once
	file_pgaas_api_proto_rawDescData []byte
)

func file_pgaas_api_proto_rawDescGZIP() []byte {
	file_pgaas_api_proto_rawDescOnce.Do(func() {
		file_pgaas_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pgaas_api_proto_rawDesc), len(file_pgaas_api_proto_rawDesc)))
	})
	return file_pgaas_api_proto_rawDescData
}

var file_pgaas_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pgaas_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_pgaas_api_proto_goTypes = []any{
	(PgInstanceIsolation)(0),                  // 0: velez_api.PgInstanceIsolation
	(*PgInstance)(nil),                        // 1: velez_api.PgInstance
	(*ListPgInstances)(nil),                   // 2: velez_api.ListPgInstances
	(*CreatePgInstance)(nil),                  // 3: velez_api.CreatePgInstance
	(*DropPgInstance)(nil),                    // 4: velez_api.DropPgInstance
	(*GetPgInstanceCredentials)(nil),          // 5: velez_api.GetPgInstanceCredentials
	(*ListPgInstances_Request)(nil),           // 6: velez_api.ListPgInstances.Request
	(*ListPgInstances_Response)(nil),          // 7: velez_api.ListPgInstances.Response
	(*CreatePgInstance_Request)(nil),          // 8: velez_api.CreatePgInstance.Request
	(*CreatePgInstance_Response)(nil),         // 9: velez_api.CreatePgInstance.Response
	(*DropPgInstance_Request)(nil),            // 10: velez_api.DropPgInstance.Request
	(*DropPgInstance_Response)(nil),           // 11: velez_api.DropPgInstance.Response
	(*GetPgInstanceCredentials_Request)(nil),  // 12: velez_api.GetPgInstanceCredentials.Request
	(*GetPgInstanceCredentials_Response)(nil), // 13: velez_api.GetPgInstanceCredentials.Response
	(*timestamppb.Timestamp)(nil),             // 14: google.protobuf.Timestamp
	(*Paging)(nil),                            // 15: velez_api.Paging
}
var file_pgaas_api_proto_depIdxs = []int32{
	14, // 0: velez_api.PgInstance.created_at:type_name -> google.protobuf.Timestamp
	14, // 1: velez_api.PgInstance.updated_at:type_name -> google.protobuf.Timestamp
	15, // 2: velez_api.ListPgInstances.Request.paging:type_name -> velez_api.Paging
	1,  // 3: velez_api.ListPgInstances.Response.instances:type_name -> velez_api.PgInstance
	1,  // 4: velez_api.CreatePgInstance.Response.instance:type_name -> velez_api.PgInstance
	6,  // 5: velez_api.PostgresAPI.ListPgInstances:input_type -> velez_api.ListPgInstances.Request
	8,  // 6: velez_api.PostgresAPI.CreatePgInstance:input_type -> velez_api.CreatePgInstance.Request
	10, // 7: velez_api.PostgresAPI.DropPgInstance:input_type -> velez_api.DropPgInstance.Request
	12, // 8: velez_api.PostgresAPI.GetPgInstanceCredentials:input_type -> velez_api.GetPgInstanceCredentials.Request
	7,  // 9: velez_api.PostgresAPI.ListPgInstances:output_type -> velez_api.ListPgInstances.Response
	9,  // 10: velez_api.PostgresAPI.CreatePgInstance:output_type -> velez_api.CreatePgInstance.Response
	11, // 11: velez_api.PostgresAPI.DropPgInstance:output_type -> velez_api.DropPgInstance.Response
	13, // 12: velez_api.PostgresAPI.GetPgInstanceCredentials:output_type -> velez_api.GetPgInstanceCredentials.Response
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pgaas_api_proto_init() }
func file_pgaas_api_proto_init() {
	if File_pgaas_api_proto != nil {
		return
	}
	file_velez_common_proto_init()
	file_pgaas_api_proto_msgTypes[0].OneofWrappers = []any{}
	file_pgaas_api_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pgaas_api_proto_rawDesc), len(file_pgaas_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pgaas_api_proto_goTypes,
		DependencyIndexes: file_pgaas_api_proto_depIdxs,
		EnumInfos:         file_pgaas_api_proto_enumTypes,
		MessageInfos:      file_pgaas_api_proto_msgTypes,
	}.Build()
	File_pgaas_api_proto = out.File
	file_pgaas_api_proto_goTypes = nil
	file_pgaas_api_proto_depIdxs = nil
}
