// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.28.3
// source: runners_api.proto

package velez_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RunnersAPI_ListRunners_FullMethodName          = "/velez_api.RunnersAPI/ListRunners"
	RunnersAPI_CreateRunner_FullMethodName         = "/velez_api.RunnersAPI/CreateRunner"
	RunnersAPI_DropRunner_FullMethodName           = "/velez_api.RunnersAPI/DropRunner"
	RunnersAPI_ReregisterRunner_FullMethodName     = "/velez_api.RunnersAPI/ReregisterRunner"
	RunnersAPI_GetRunnerCredentials_FullMethodName = "/velez_api.RunnersAPI/GetRunnerCredentials"
	RunnersAPI_GetRunnerConfig_FullMethodName      = "/velez_api.RunnersAPI/GetRunnerConfig"
	RunnersAPI_UpdateRunnerConfig_FullMethodName   = "/velez_api.RunnersAPI/UpdateRunnerConfig"
	RunnersAPI_RedeployRunner_FullMethodName       = "/velez_api.RunnersAPI/RedeployRunner"
)

// RunnersAPIClient is the client API for RunnersAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RunnersAPI - Runners-as-a-Service. A runner is a normal Velez service
// (velez.services / deployment_specifications / deployments), with only the
// runner-specific facts (provider, scope, target, labels, secret_ref) held in
// velez.runners. Git-agnostic by design: GitHub Actions is the first
// RunnerProvider, GitLab and others are additional providers under this same
// contract, not separate contracts. Structured after PostgresAPI.
type RunnersAPIClient interface {
	ListRunners(ctx context.Context, in *ListRunners_Request, opts ...grpc.CallOption) (*ListRunners_Response, error)
	CreateRunner(ctx context.Context, in *CreateRunner_Request, opts ...grpc.CallOption) (*CreateRunner_Response, error)
	DropRunner(ctx context.Context, in *DropRunner_Request, opts ...grpc.CallOption) (*DropRunner_Response, error)
	// ReregisterRunner unregisters and re-registers the runner's existing
	// container in place, reusing its already-stored registration token - no
	// new token minted, no new container deployed. A no-op unregister/register
	// for a self-registering provider (GitHub).
	ReregisterRunner(ctx context.Context, in *ReregisterRunner_Request, opts ...grpc.CallOption) (*ReregisterRunner_Response, error)
	// GetRunnerCredentials is the only RPC that resolves a secret_ref to its
	// value.
	GetRunnerCredentials(ctx context.Context, in *GetRunnerCredentials_Request, opts ...grpc.CallOption) (*GetRunnerCredentials_Response, error)
	// GetRunnerConfig reads the runner's currently stored provider config
	// (base_url, docker_image, docker_socket_address) - the values the next
	// ReregisterRunner/RedeployRunner call will apply, not necessarily what
	// the running container was deployed with.
	GetRunnerConfig(ctx context.Context, in *GetRunnerConfig_Request, opts ...grpc.CallOption) (*GetRunnerConfig_Response, error)
	// UpdateRunnerConfig persists new provider config values. It never applies
	// them to the running container - the response tells the caller which
	// follow-up action does: requires_reregister (base_url/docker_image, via
	// ReregisterRunner) and/or requires_redeploy (docker_socket_address, via
	// RedeployRunner).
	UpdateRunnerConfig(ctx context.Context, in *UpdateRunnerConfig_Request, opts ...grpc.CallOption) (*UpdateRunnerConfig_Response, error)
	// RedeployRunner recreates the runner's container from its current stored
	// deployment spec, overlaying docker_socket_address as DOCKER_HOST (or
	// clearing it back to unset) - the only way a docker_socket_address change
	// ever reaches the container, since it's a deploy-time env var, not
	// something a running container can pick up. Mirrors ReregisterRunner's
	// fire-and-forget shape.
	RedeployRunner(ctx context.Context, in *RedeployRunner_Request, opts ...grpc.CallOption) (*RedeployRunner_Response, error)
}

type runnersAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnersAPIClient(cc grpc.ClientConnInterface) RunnersAPIClient {
	return &runnersAPIClient{cc}
}

func (c *runnersAPIClient) ListRunners(ctx context.Context, in *ListRunners_Request, opts ...grpc.CallOption) (*ListRunners_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunners_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_ListRunners_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) CreateRunner(ctx context.Context, in *CreateRunner_Request, opts ...grpc.CallOption) (*CreateRunner_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRunner_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_CreateRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) DropRunner(ctx context.Context, in *DropRunner_Request, opts ...grpc.CallOption) (*DropRunner_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropRunner_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_DropRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) ReregisterRunner(ctx context.Context, in *ReregisterRunner_Request, opts ...grpc.CallOption) (*ReregisterRunner_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReregisterRunner_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_ReregisterRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) GetRunnerCredentials(ctx context.Context, in *GetRunnerCredentials_Request, opts ...grpc.CallOption) (*GetRunnerCredentials_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunnerCredentials_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_GetRunnerCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) GetRunnerConfig(ctx context.Context, in *GetRunnerConfig_Request, opts ...grpc.CallOption) (*GetRunnerConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRunnerConfig_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_GetRunnerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) UpdateRunnerConfig(ctx context.Context, in *UpdateRunnerConfig_Request, opts ...grpc.CallOption) (*UpdateRunnerConfig_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRunnerConfig_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_UpdateRunnerConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) RedeployRunner(ctx context.Context, in *RedeployRunner_Request, opts ...grpc.CallOption) (*RedeployRunner_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeployRunner_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_RedeployRunner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnersAPIServer is the server API for RunnersAPI service.
// All implementations must embed UnimplementedRunnersAPIServer
// for forward compatibility.
//
// RunnersAPI - Runners-as-a-Service. A runner is a normal Velez service
// (velez.services / deployment_specifications / deployments), with only the
// runner-specific facts (provider, scope, target, labels, secret_ref) held in
// velez.runners. Git-agnostic by design: GitHub Actions is the first
// RunnerProvider, GitLab and others are additional providers under this same
// contract, not separate contracts. Structured after PostgresAPI.
type RunnersAPIServer interface {
	ListRunners(context.Context, *ListRunners_Request) (*ListRunners_Response, error)
	CreateRunner(context.Context, *CreateRunner_Request) (*CreateRunner_Response, error)
	DropRunner(context.Context, *DropRunner_Request) (*DropRunner_Response, error)
	// ReregisterRunner unregisters and re-registers the runner's existing
	// container in place, reusing its already-stored registration token - no
	// new token minted, no new container deployed. A no-op unregister/register
	// for a self-registering provider (GitHub).
	ReregisterRunner(context.Context, *ReregisterRunner_Request) (*ReregisterRunner_Response, error)
	// GetRunnerCredentials is the only RPC that resolves a secret_ref to its
	// value.
	GetRunnerCredentials(context.Context, *GetRunnerCredentials_Request) (*GetRunnerCredentials_Response, error)
	// GetRunnerConfig reads the runner's currently stored provider config
	// (base_url, docker_image, docker_socket_address) - the values the next
	// ReregisterRunner/RedeployRunner call will apply, not necessarily what
	// the running container was deployed with.
	GetRunnerConfig(context.Context, *GetRunnerConfig_Request) (*GetRunnerConfig_Response, error)
	// UpdateRunnerConfig persists new provider config values. It never applies
	// them to the running container - the response tells the caller which
	// follow-up action does: requires_reregister (base_url/docker_image, via
	// ReregisterRunner) and/or requires_redeploy (docker_socket_address, via
	// RedeployRunner).
	UpdateRunnerConfig(context.Context, *UpdateRunnerConfig_Request) (*UpdateRunnerConfig_Response, error)
	// RedeployRunner recreates the runner's container from its current stored
	// deployment spec, overlaying docker_socket_address as DOCKER_HOST (or
	// clearing it back to unset) - the only way a docker_socket_address change
	// ever reaches the container, since it's a deploy-time env var, not
	// something a running container can pick up. Mirrors ReregisterRunner's
	// fire-and-forget shape.
	RedeployRunner(context.Context, *RedeployRunner_Request) (*RedeployRunner_Response, error)
	mustEmbedUnimplementedRunnersAPIServer()
}

// UnimplementedRunnersAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRunnersAPIServer struct{}

func (UnimplementedRunnersAPIServer) ListRunners(context.Context, *ListRunners_Request) (*ListRunners_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRunners not implemented")
}
func (UnimplementedRunnersAPIServer) CreateRunner(context.Context, *CreateRunner_Request) (*CreateRunner_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRunner not implemented")
}
func (UnimplementedRunnersAPIServer) DropRunner(context.Context, *DropRunner_Request) (*DropRunner_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DropRunner not implemented")
}
func (UnimplementedRunnersAPIServer) ReregisterRunner(context.Context, *ReregisterRunner_Request) (*ReregisterRunner_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ReregisterRunner not implemented")
}
func (UnimplementedRunnersAPIServer) GetRunnerCredentials(context.Context, *GetRunnerCredentials_Request) (*GetRunnerCredentials_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunnerCredentials not implemented")
}
func (UnimplementedRunnersAPIServer) GetRunnerConfig(context.Context, *GetRunnerConfig_Request) (*GetRunnerConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRunnerConfig not implemented")
}
func (UnimplementedRunnersAPIServer) UpdateRunnerConfig(context.Context, *UpdateRunnerConfig_Request) (*UpdateRunnerConfig_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRunnerConfig not implemented")
}
func (UnimplementedRunnersAPIServer) RedeployRunner(context.Context, *RedeployRunner_Request) (*RedeployRunner_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeployRunner not implemented")
}
func (UnimplementedRunnersAPIServer) mustEmbedUnimplementedRunnersAPIServer() {}
func (UnimplementedRunnersAPIServer) testEmbeddedByValue()                    {}

// UnsafeRunnersAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnersAPIServer will
// result in compilation errors.
type UnsafeRunnersAPIServer interface {
	mustEmbedUnimplementedRunnersAPIServer()
}

func RegisterRunnersAPIServer(s grpc.ServiceRegistrar, srv RunnersAPIServer) {
	// If the following call panics, it indicates UnimplementedRunnersAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RunnersAPI_ServiceDesc, srv)
}

func _RunnersAPI_ListRunners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunners_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).ListRunners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_ListRunners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).ListRunners(ctx, req.(*ListRunners_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_CreateRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRunner_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).CreateRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_CreateRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).CreateRunner(ctx, req.(*CreateRunner_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_DropRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropRunner_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).DropRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_DropRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).DropRunner(ctx, req.(*DropRunner_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_ReregisterRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReregisterRunner_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).ReregisterRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_ReregisterRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).ReregisterRunner(ctx, req.(*ReregisterRunner_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_GetRunnerCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerCredentials_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).GetRunnerCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_GetRunnerCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).GetRunnerCredentials(ctx, req.(*GetRunnerCredentials_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_GetRunnerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunnerConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).GetRunnerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_GetRunnerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).GetRunnerConfig(ctx, req.(*GetRunnerConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_UpdateRunnerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRunnerConfig_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).UpdateRunnerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_UpdateRunnerConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).UpdateRunnerConfig(ctx, req.(*UpdateRunnerConfig_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_RedeployRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeployRunner_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).RedeployRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_RedeployRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).RedeployRunner(ctx, req.(*RedeployRunner_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnersAPI_ServiceDesc is the grpc.ServiceDesc for RunnersAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnersAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "velez_api.RunnersAPI",
	HandlerType: (*RunnersAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRunners",
			Handler:    _RunnersAPI_ListRunners_Handler,
		},
		{
			MethodName: "CreateRunner",
			Handler:    _RunnersAPI_CreateRunner_Handler,
		},
		{
			MethodName: "DropRunner",
			Handler:    _RunnersAPI_DropRunner_Handler,
		},
		{
			MethodName: "ReregisterRunner",
			Handler:    _RunnersAPI_ReregisterRunner_Handler,
		},
		{
			MethodName: "GetRunnerCredentials",
			Handler:    _RunnersAPI_GetRunnerCredentials_Handler,
		},
		{
			MethodName: "GetRunnerConfig",
			Handler:    _RunnersAPI_GetRunnerConfig_Handler,
		},
		{
			MethodName: "UpdateRunnerConfig",
			Handler:    _RunnersAPI_UpdateRunnerConfig_Handler,
		},
		{
			MethodName: "RedeployRunner",
			Handler:    _RunnersAPI_RedeployRunner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runners_api.proto",
}
