// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.3
// source: runners_api.proto

package velez_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RunnersAPI_ListRunners_FullMethodName  = "/velez_api.RunnersAPI/ListRunners"
	RunnersAPI_CreateRunner_FullMethodName = "/velez_api.RunnersAPI/CreateRunner"
	RunnersAPI_DropRunner_FullMethodName   = "/velez_api.RunnersAPI/DropRunner"
)

// RunnersAPIClient is the client API for RunnersAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnersAPIClient interface {
	ListRunners(ctx context.Context, in *ListRunners_Request, opts ...grpc.CallOption) (*ListRunners_Response, error)
	CreateRunner(ctx context.Context, in *CreateRunner_Request, opts ...grpc.CallOption) (*CreateRunner_Response, error)
	DropRunner(ctx context.Context, in *DropRunner_Request, opts ...grpc.CallOption) (*DropRunner_Response, error)
}

type runnersAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnersAPIClient(cc grpc.ClientConnInterface) RunnersAPIClient {
	return &runnersAPIClient{cc}
}

func (c *runnersAPIClient) ListRunners(ctx context.Context, in *ListRunners_Request, opts ...grpc.CallOption) (*ListRunners_Response, error) {
	out := new(ListRunners_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_ListRunners_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) CreateRunner(ctx context.Context, in *CreateRunner_Request, opts ...grpc.CallOption) (*CreateRunner_Response, error) {
	out := new(CreateRunner_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_CreateRunner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runnersAPIClient) DropRunner(ctx context.Context, in *DropRunner_Request, opts ...grpc.CallOption) (*DropRunner_Response, error) {
	out := new(DropRunner_Response)
	err := c.cc.Invoke(ctx, RunnersAPI_DropRunner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RunnersAPIServer is the server API for RunnersAPI service.
// All implementations must embed UnimplementedRunnersAPIServer
// for forward compatibility
type RunnersAPIServer interface {
	ListRunners(context.Context, *ListRunners_Request) (*ListRunners_Response, error)
	CreateRunner(context.Context, *CreateRunner_Request) (*CreateRunner_Response, error)
	DropRunner(context.Context, *DropRunner_Request) (*DropRunner_Response, error)
	mustEmbedUnimplementedRunnersAPIServer()
}

// UnimplementedRunnersAPIServer must be embedded to have forward compatible implementations.
type UnimplementedRunnersAPIServer struct {
}

func (UnimplementedRunnersAPIServer) ListRunners(context.Context, *ListRunners_Request) (*ListRunners_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRunners not implemented")
}
func (UnimplementedRunnersAPIServer) CreateRunner(context.Context, *CreateRunner_Request) (*CreateRunner_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRunner not implemented")
}
func (UnimplementedRunnersAPIServer) DropRunner(context.Context, *DropRunner_Request) (*DropRunner_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropRunner not implemented")
}
func (UnimplementedRunnersAPIServer) mustEmbedUnimplementedRunnersAPIServer() {}

// UnsafeRunnersAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnersAPIServer will
// result in compilation errors.
type UnsafeRunnersAPIServer interface {
	mustEmbedUnimplementedRunnersAPIServer()
}

func RegisterRunnersAPIServer(s grpc.ServiceRegistrar, srv RunnersAPIServer) {
	s.RegisterService(&RunnersAPI_ServiceDesc, srv)
}

func _RunnersAPI_ListRunners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunners_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).ListRunners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_ListRunners_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).ListRunners(ctx, req.(*ListRunners_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_CreateRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRunner_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).CreateRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_CreateRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).CreateRunner(ctx, req.(*CreateRunner_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RunnersAPI_DropRunner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropRunner_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RunnersAPIServer).DropRunner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RunnersAPI_DropRunner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RunnersAPIServer).DropRunner(ctx, req.(*DropRunner_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RunnersAPI_ServiceDesc is the grpc.ServiceDesc for RunnersAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnersAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "velez_api.RunnersAPI",
	HandlerType: (*RunnersAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRunners",
			Handler:    _RunnersAPI_ListRunners_Handler,
		},
		{
			MethodName: "CreateRunner",
			Handler:    _RunnersAPI_CreateRunner_Handler,
		},
		{
			MethodName: "DropRunner",
			Handler:    _RunnersAPI_DropRunner_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runners_api.proto",
}
