// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: tasks.proto

package velez_api

import (
	_ "go.redsock.ru/protoc-gen-npm/npmplugin"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus_Status int32

const (
	TaskStatus_UNKNOWN TaskStatus_Status = 0
	TaskStatus_PENDING TaskStatus_Status = 1
	TaskStatus_RUNNING TaskStatus_Status = 2
	TaskStatus_DONE    TaskStatus_Status = 3
	TaskStatus_FAILED  TaskStatus_Status = 4
)

// Enum value maps for TaskStatus_Status.
var (
	TaskStatus_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "PENDING",
		2: "RUNNING",
		3: "DONE",
		4: "FAILED",
	}
	TaskStatus_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"PENDING": 1,
		"RUNNING": 2,
		"DONE":    3,
		"FAILED":  4,
	}
)

func (x TaskStatus_Status) Enum() *TaskStatus_Status {
	p := new(TaskStatus_Status)
	*p = x
	return p
}

func (x TaskStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_tasks_proto_enumTypes[0].Descriptor()
}

func (TaskStatus_Status) Type() protoreflect.EnumType {
	return &file_tasks_proto_enumTypes[0]
}

func (x TaskStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus_Status.Descriptor instead.
func (TaskStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{1, 0}
}

type WatchTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTask) Reset() {
	*x = WatchTask{}
	mi := &file_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTask) ProtoMessage() {}

func (x *WatchTask) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTask.ProtoReflect.Descriptor instead.
func (*WatchTask) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{0}
}

type TaskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus_Status      `protobuf:"varint,1,opt,name=status,proto3,enum=velez_api.TaskStatus_Status" json:"status,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStatus) Reset() {
	*x = TaskStatus{}
	mi := &file_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatus) ProtoMessage() {}

func (x *TaskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatus.ProtoReflect.Descriptor instead.
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *TaskStatus) GetStatus() TaskStatus_Status {
	if x != nil {
		return x.Status
	}
	return TaskStatus_UNKNOWN
}

func (x *TaskStatus) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *TaskStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateSmerdTaskPayload is the task context for the "create_smerd" action.
// It carries only the business data jobs need to hand off to one another;
// per-job execution status lives separately in the task engine's own tables.
type CreateSmerdTaskPayload struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Request *CreateSmerd_Request   `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Set once the image has been prepared/inspected.
	ImageId *string `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3,oneof" json:"image_id,omitempty"`
	// Set once the container has been created.
	ContainerId   *string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3,oneof" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSmerdTaskPayload) Reset() {
	*x = CreateSmerdTaskPayload{}
	mi := &file_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSmerdTaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSmerdTaskPayload) ProtoMessage() {}

func (x *CreateSmerdTaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSmerdTaskPayload.ProtoReflect.Descriptor instead.
func (*CreateSmerdTaskPayload) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSmerdTaskPayload) GetRequest() *CreateSmerd_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CreateSmerdTaskPayload) GetImageId() string {
	if x != nil && x.ImageId != nil {
		return *x.ImageId
	}
	return ""
}

func (x *CreateSmerdTaskPayload) GetContainerId() string {
	if x != nil && x.ContainerId != nil {
		return *x.ContainerId
	}
	return ""
}

// CreateServiceTaskPayload is the task context for the "create_service" action.
type CreateServiceTaskPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceTaskPayload) Reset() {
	*x = CreateServiceTaskPayload{}
	mi := &file_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceTaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceTaskPayload) ProtoMessage() {}

func (x *CreateServiceTaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceTaskPayload.ProtoReflect.Descriptor instead.
func (*CreateServiceTaskPayload) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *CreateServiceTaskPayload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// AssembleConfigTaskPayload is the task context for the "assemble_config" action.
type AssembleConfigTaskPayload struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServiceName string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ImageName   string                 `protobuf:"bytes,2,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	// Set once the scratch image has been pulled/inspected.
	ImageLabels map[string]string `protobuf:"bytes,3,rep,name=image_labels,json=imageLabels,proto3" json:"image_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ImageTags   []string          `protobuf:"bytes,4,rep,name=image_tags,json=imageTags,proto3" json:"image_tags,omitempty"`
	// Set once the scratch container has been created.
	ContainerId *string `protobuf:"bytes,5,opt,name=container_id,json=containerId,proto3,oneof" json:"container_id,omitempty"`
	// Set once config metadata has been resolved and its raw content fetched
	// from the container.
	ConfigName    *string `protobuf:"bytes,6,opt,name=config_name,json=configName,proto3,oneof" json:"config_name,omitempty"`
	ConfigVersion *string `protobuf:"bytes,7,opt,name=config_version,json=configVersion,proto3,oneof" json:"config_version,omitempty"`
	// matreshka_api.ConfigTypePrefix's enum name, e.g. "plain"/"verv"/"pg".
	// Kept as a string rather than the typed enum to avoid a proto dependency
	// on the matreshka_api package (see moti.yaml deps for its pinned version).
	ConfType     *string       `protobuf:"bytes,8,opt,name=conf_type,json=confType,proto3,oneof" json:"conf_type,omitempty"`
	ConfigFormat *ConfigFormat `protobuf:"varint,9,opt,name=config_format,json=configFormat,proto3,enum=velez_api.ConfigFormat,oneof" json:"config_format,omitempty"`
	ContentRaw   []byte        `protobuf:"bytes,10,opt,name=content_raw,json=contentRaw,proto3,oneof" json:"content_raw,omitempty"`
	// Set once content_raw has been parsed into evon (env) format.
	Content       []byte `protobuf:"bytes,11,opt,name=content,proto3,oneof" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssembleConfigTaskPayload) Reset() {
	*x = AssembleConfigTaskPayload{}
	mi := &file_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssembleConfigTaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssembleConfigTaskPayload) ProtoMessage() {}

func (x *AssembleConfigTaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssembleConfigTaskPayload.ProtoReflect.Descriptor instead.
func (*AssembleConfigTaskPayload) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *AssembleConfigTaskPayload) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AssembleConfigTaskPayload) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

func (x *AssembleConfigTaskPayload) GetImageLabels() map[string]string {
	if x != nil {
		return x.ImageLabels
	}
	return nil
}

func (x *AssembleConfigTaskPayload) GetImageTags() []string {
	if x != nil {
		return x.ImageTags
	}
	return nil
}

func (x *AssembleConfigTaskPayload) GetContainerId() string {
	if x != nil && x.ContainerId != nil {
		return *x.ContainerId
	}
	return ""
}

func (x *AssembleConfigTaskPayload) GetConfigName() string {
	if x != nil && x.ConfigName != nil {
		return *x.ConfigName
	}
	return ""
}

func (x *AssembleConfigTaskPayload) GetConfigVersion() string {
	if x != nil && x.ConfigVersion != nil {
		return *x.ConfigVersion
	}
	return ""
}

func (x *AssembleConfigTaskPayload) GetConfType() string {
	if x != nil && x.ConfType != nil {
		return *x.ConfType
	}
	return ""
}

func (x *AssembleConfigTaskPayload) GetConfigFormat() ConfigFormat {
	if x != nil && x.ConfigFormat != nil {
		return *x.ConfigFormat
	}
	return ConfigFormat_yaml
}

func (x *AssembleConfigTaskPayload) GetContentRaw() []byte {
	if x != nil {
		return x.ContentRaw
	}
	return nil
}

func (x *AssembleConfigTaskPayload) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

// CopyToVolumeTaskPayload is the task context for the "copy_to_volume" action.
type CopyToVolumeTaskPayload struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	VolumeName string                 `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// Path inside the loader container -> file content. A dynamic number of
	// copy_file_<n> jobs are built from this map, one per entry, sorted by
	// path so job naming stays stable across BuildJobs re-runs.
	PathToFiles map[string][]byte `protobuf:"bytes,2,rep,name=path_to_files,json=pathToFiles,proto3" json:"path_to_files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Set once the loader container has been created.
	ContainerId   *string `protobuf:"bytes,3,opt,name=container_id,json=containerId,proto3,oneof" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyToVolumeTaskPayload) Reset() {
	*x = CopyToVolumeTaskPayload{}
	mi := &file_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyToVolumeTaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyToVolumeTaskPayload) ProtoMessage() {}

func (x *CopyToVolumeTaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyToVolumeTaskPayload.ProtoReflect.Descriptor instead.
func (*CopyToVolumeTaskPayload) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *CopyToVolumeTaskPayload) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *CopyToVolumeTaskPayload) GetPathToFiles() map[string][]byte {
	if x != nil {
		return x.PathToFiles
	}
	return nil
}

func (x *CopyToVolumeTaskPayload) GetContainerId() string {
	if x != nil && x.ContainerId != nil {
		return *x.ContainerId
	}
	return ""
}

type WatchTask_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTask_Request) Reset() {
	*x = WatchTask_Request{}
	mi := &file_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTask_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTask_Request) ProtoMessage() {}

func (x *WatchTask_Request) ProtoReflect() protoreflect.Message {
	mi := &file_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTask_Request.ProtoReflect.Descriptor instead.
func (*WatchTask_Request) Descriptor() ([]byte, []int) {
	return file_tasks_proto_rawDescGZIP(), []int{0, 0}
}

func (x *WatchTask_Request) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *WatchTask_Request) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_tasks_proto protoreflect.FileDescriptor

const file_tasks_proto_rawDesc = "" +
	"\n" +
	"\vtasks.proto\x12\tvelez_api\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\tnpm.proto\x1a\x0fvelez_api.proto\x1a\x12velez_common.proto\"K\n" +
	"\tWatchTask\x1a>\n" +
	"\aRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xe9\x01\n" +
	"\n" +
	"TaskStatus\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.velez_api.TaskStatus.StatusR\x06status\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"E\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aPENDING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\b\n" +
	"\x04DONE\x10\x03\x12\n" +
	"\n" +
	"\x06FAILED\x10\x04B\b\n" +
	"\x06_error\"\xb8\x01\n" +
	"\x16CreateSmerdTaskPayload\x128\n" +
	"\arequest\x18\x01 \x01(\v2\x1e.velez_api.CreateSmerd.RequestR\arequest\x12\x1e\n" +
	"\bimage_id\x18\x02 \x01(\tH\x00R\aimageId\x88\x01\x01\x12&\n" +
	"\fcontainer_id\x18\x03 \x01(\tH\x01R\vcontainerId\x88\x01\x01B\v\n" +
	"\t_image_idB\x0f\n" +
	"\r_container_id\".\n" +
	"\x18CreateServiceTaskPayload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xaa\x05\n" +
	"\x19AssembleConfigTaskPayload\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"image_name\x18\x02 \x01(\tR\timageName\x12X\n" +
	"\fimage_labels\x18\x03 \x03(\v25.velez_api.AssembleConfigTaskPayload.ImageLabelsEntryR\vimageLabels\x12\x1d\n" +
	"\n" +
	"image_tags\x18\x04 \x03(\tR\timageTags\x12&\n" +
	"\fcontainer_id\x18\x05 \x01(\tH\x00R\vcontainerId\x88\x01\x01\x12$\n" +
	"\vconfig_name\x18\x06 \x01(\tH\x01R\n" +
	"configName\x88\x01\x01\x12*\n" +
	"\x0econfig_version\x18\a \x01(\tH\x02R\rconfigVersion\x88\x01\x01\x12 \n" +
	"\tconf_type\x18\b \x01(\tH\x03R\bconfType\x88\x01\x01\x12A\n" +
	"\rconfig_format\x18\t \x01(\x0e2\x17.velez_api.ConfigFormatH\x04R\fconfigFormat\x88\x01\x01\x12$\n" +
	"\vcontent_raw\x18\n" +
	" \x01(\fH\x05R\n" +
	"contentRaw\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\v \x01(\fH\x06R\acontent\x88\x01\x01\x1a>\n" +
	"\x10ImageLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0f\n" +
	"\r_container_idB\x0e\n" +
	"\f_config_nameB\x11\n" +
	"\x0f_config_versionB\f\n" +
	"\n" +
	"_conf_typeB\x10\n" +
	"\x0e_config_formatB\x0e\n" +
	"\f_content_rawB\n" +
	"\n" +
	"\b_content\"\x8c\x02\n" +
	"\x17CopyToVolumeTaskPayload\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12W\n" +
	"\rpath_to_files\x18\x02 \x03(\v23.velez_api.CopyToVolumeTaskPayload.PathToFilesEntryR\vpathToFiles\x12&\n" +
	"\fcontainer_id\x18\x03 \x01(\tH\x00R\vcontainerId\x88\x01\x01\x1a>\n" +
	"\x10PathToFilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B\x0f\n" +
	"\r_container_id2h\n" +
	"\bTasksApi\x12\\\n" +
	"\tWatchTask\x12\x1c.velez_api.WatchTask.Request\x1a\x15.velez_api.TaskStatus\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/tasks/watch0\x01BC\x92\x82\x19\x10@vervstack/velezZ-go.vervstack.ru/velez/pkg/velez_api;velez_apib\x06proto3"

var (
	file_tasks_proto_rawDescOnce sync.Once
	file_tasks_proto_rawDescData []byte
)

func file_tasks_proto_rawDescGZIP() []byte {
	file_tasks_proto_rawDescOnce.Do(func() {
		file_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tasks_proto_rawDesc), len(file_tasks_proto_rawDesc)))
	})
	return file_tasks_proto_rawDescData
}

var file_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_tasks_proto_goTypes = []any{
	(TaskStatus_Status)(0),            // 0: velez_api.TaskStatus.Status
	(*WatchTask)(nil),                 // 1: velez_api.WatchTask
	(*TaskStatus)(nil),                // 2: velez_api.TaskStatus
	(*CreateSmerdTaskPayload)(nil),    // 3: velez_api.CreateSmerdTaskPayload
	(*CreateServiceTaskPayload)(nil),  // 4: velez_api.CreateServiceTaskPayload
	(*AssembleConfigTaskPayload)(nil), // 5: velez_api.AssembleConfigTaskPayload
	(*CopyToVolumeTaskPayload)(nil),   // 6: velez_api.CopyToVolumeTaskPayload
	(*WatchTask_Request)(nil),         // 7: velez_api.WatchTask.Request
	nil,                               // 8: velez_api.AssembleConfigTaskPayload.ImageLabelsEntry
	nil,                               // 9: velez_api.CopyToVolumeTaskPayload.PathToFilesEntry
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*CreateSmerd_Request)(nil),       // 11: velez_api.CreateSmerd.Request
	(ConfigFormat)(0),                 // 12: velez_api.ConfigFormat
}
var file_tasks_proto_depIdxs = []int32{
	0,  // 0: velez_api.TaskStatus.status:type_name -> velez_api.TaskStatus.Status
	10, // 1: velez_api.TaskStatus.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: velez_api.CreateSmerdTaskPayload.request:type_name -> velez_api.CreateSmerd.Request
	8,  // 3: velez_api.AssembleConfigTaskPayload.image_labels:type_name -> velez_api.AssembleConfigTaskPayload.ImageLabelsEntry
	12, // 4: velez_api.AssembleConfigTaskPayload.config_format:type_name -> velez_api.ConfigFormat
	9,  // 5: velez_api.CopyToVolumeTaskPayload.path_to_files:type_name -> velez_api.CopyToVolumeTaskPayload.PathToFilesEntry
	7,  // 6: velez_api.TasksApi.WatchTask:input_type -> velez_api.WatchTask.Request
	2,  // 7: velez_api.TasksApi.WatchTask:output_type -> velez_api.TaskStatus
	7,  // [7:8] is the sub-list for method output_type
	6,  // [6:7] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tasks_proto_init() }
func file_tasks_proto_init() {
	if File_tasks_proto != nil {
		return
	}
	file_velez_api_proto_init()
	file_velez_common_proto_init()
	file_tasks_proto_msgTypes[1].OneofWrappers = []any{}
	file_tasks_proto_msgTypes[2].OneofWrappers = []any{}
	file_tasks_proto_msgTypes[4].OneofWrappers = []any{}
	file_tasks_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tasks_proto_rawDesc), len(file_tasks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tasks_proto_goTypes,
		DependencyIndexes: file_tasks_proto_depIdxs,
		EnumInfos:         file_tasks_proto_enumTypes,
		MessageInfos:      file_tasks_proto_msgTypes,
	}.Build()
	File_tasks_proto = out.File
	file_tasks_proto_goTypes = nil
	file_tasks_proto_depIdxs = nil
}
