// Code generated by RedSock CLI. DO NOT EDIT.

package config

type EnvironmentConfig struct {
	AvailablePorts     []int
	ClusterPgDsn       string
	CPUDefault         float64
	CustomPassToKey    string
	DisableAPISecurity bool
	LogFormat          string
	LogLevel           string
	MakoshExposePort   bool
	MakoshImage        string
	MakoshIsEnabled    bool
	MakoshKey          string
	MakoshPort         int
	MakoshURL          string
	MasterNodeAddress  string
	MatreshkaImage     string
	MatreshkaIsEnabled bool
	MatreshkaKey       string
	MatreshkaPort      int
	MemorySwapMb       int
	RAMMbDefault       int
	ShutDownOnExit     bool
	VpnServerURL       string
}

const (
	LogFormat_Text = "TEXT"
	LogFormat_Json = "JSON"
)

const (
	LogLevel_Trace = "Trace"
	LogLevel_Debug = "Debug"
	LogLevel_Warn  = "Warn"
	LogLevel_Info  = "Info"
	LogLevel_Error = "Error"
	LogLevel_Fatal = "Fatal"
	LogLevel_Panic = "Panic"
)
