// Code generated by RedSock CLI. DO NOT EDIT.

package config

// EnvironmentConfig holds parsed configuration values for this section.
type EnvironmentConfig struct {
	AvailablePorts     []int
	ClusterPgDsn       string
	ContainerSuffix    string
	CPUDefault         float64
	CustomLabels       []string
	DisableAPISecurity bool
	Environments       []string
	LocalStatePath     string
	LogFormat          string
	LogLevel           string
	MakoshExposePort   bool
	MakoshImage        string
	MakoshIsEnabled    bool
	MakoshKey          string
	MakoshPort         int
	MakoshURL          string
	MasterNodeAddress  string
	MatreshkaImage     string
	MatreshkaIsEnabled bool
	MatreshkaKey       string
	MatreshkaPort      int
	MemorySwapMb       int
	NodeRegion         string
	RAMMbDefault       int
	ShutDownOnExit     bool
	VpnServerURL       string
}

// LogFormat enumerates the allowed values for the LogFormat field.
const (
	LogFormatText = "TEXT"
	LogFormatJSON = "JSON"
)

// LogLevel enumerates the allowed values for the LogLevel field.
const (
	LogLevelTrace = "Trace"
	LogLevelDebug = "Debug"
	LogLevelWarn  = "Warn"
	LogLevelInfo  = "Info"
	LogLevelError = "Error"
	LogLevelFatal = "Fatal"
	LogLevelPanic = "Panic"
)
