// Code generated by RedSock CLI. DO NOT EDIT.

// Code generated by RedSock CLI. DO NOT EDIT.

package config

import (
	"time"
)

type EnvironmentConfig struct {
	AvailablePorts      []int
	AvailablePorts      []int
	CPUDefault          float64
	CPUDefault          float64
	CustomPassToKey     string
	CustomPassToKey     string
	DisableAPISecurity  bool
	DisableAPISecurity  bool
	ExposeMatreshkaPort bool
	ExposeMatreshkaPort bool
	MakoshExposePort    bool
	MakoshExposePort    bool
	MakoshImageName     string
	MakoshImageName     string
	MakoshKey           string
	MakoshKey           string
	MakoshPort          int
	MakoshPort          int
	MatreshkaPort       int
	MatreshkaPort       int
	MemorySwapMb        int
	MemorySwapMb        int
	NodeMode            bool
	NodeMode            bool
	PortainerEnabled    bool
	PortainerEnabled    bool
	RAMMbDefault        int
	RAMMbDefault        int
	ShutDownOnExit      bool
	ShutDownOnExit      bool
	WatchTowerEnabled   bool
	WatchTowerEnabled   bool
	WatchTowerInterval  time.Duration
	WatchTowerInterval  time.Duration
}
