syntax = "proto3";

package velez_api;

import "google/api/annotations.proto";
import "npm.proto";

import "velez_api.proto";
import "velez_common.proto";

option go_package = "go.vervstack.ru/velez/pkg/velez_api;velez_api";
option (npm_package) = "@vervstack/velez";

service ControlPlaneAPI {
  rpc EnablePlugin(EnablePlugin.Request) returns (EnablePlugin.Response) {
    option (google.api.http) = {
      post: "/api/control_plane/plugin/enable"
      body: "*"
    };
  }

  // ConnectSlave - used by other Velez nodes to connect to cluster
  rpc ConnectSlave(ConnectSlave.Request) returns (ConnectSlave.Response) {
    option (google.api.http) = {
      post: "/api/control_plane/slave/connect"
      body: "*"
    };
  }

  rpc ListNodes(ListNodes.Request) returns (ListNodes.Response) {
    option (google.api.http) = {
      post: "/api/control_plane/nodes/list"
      body: "*"
    };
  }

  rpc ListPlugins(ListPlugins.Request) returns (ListPlugins.Response) {
    option (google.api.http) = {
      get: "/api/control_plane/plugins"
    };
  }
}

message ListVervPlugins {
  message Request {

  }
  message Response {
    repeated VervPlugin plugins = 1;
  }
}


message VervPlugin  {
  VervPluginType type = 1;
  optional uint32 port = 2;
  State state = 3;

  enum State {
    unknown = 0;
    running = 1;
    warning = 2;
    dead = 3;
    disabled = 4;
  }
}

enum VervPluginType {
  unknown_service_type = 0;
  matreshka = 1;
  makosh = 2;

  webserver = 3;
  headscale = 4;

  portainer = 5;

  statefull_pg = 6;
}

message EnablePlugin {
  message Request {
    VervPluginType plugin = 1;
    oneof payload {
      EnableStatefullCluster statefull_cluster = 2;
      EnableHeadscaleServer headscale_server = 3;
    }
  }

  message Response {}
}

message InitMaster {
  message Request{};

  message Response{};
}

message ConnectSlave {
  message Request {}

  message Response {}
}


message EnableStatefullCluster {
  optional bool is_expose_port = 1;
  optional uint64 expose_to_port = 2;
}

message EnableHeadscaleServer {
  oneof payload {
    DeployHeadscaleConfig deploy_config = 1;
    ExternalHeadscaleConnection external_connect = 2;
  }

  message ExternalHeadscaleConnection {
    string url = 1;
    string token = 2;
  }

  message DeployHeadscaleConfig {
    // Headscale must export any port.
    // Using custom_port allows you to specify the port to expose to
    optional uint32 custom_port = 1;
    // Using custom_image you can specify the exact image to deploy
    optional string custom_image = 2;
  }
}

message ListNodes {
  message Request {
    Paging paging = 1;
  }
  message Response {
    repeated NodeBaseInfo nodes = 1;
    uint64 total = 2;
  }
}

message Plugin {
  VervPluginType type = 1;
  VervPlugin.State state = 2;
  string service_name = 3;
}

message ListPlugins {
  message Request {}
  message Response {
    repeated Plugin plugins = 1;
  }
}