name: branch-push
run-name: ${{ github.REF_NAME }} pull request
on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  create-pr:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    steps:
      - name: Create PR
        uses: RedSockActions/create_pr@v0.0.10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  unit-test:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Test
        run: go test -tags github_wf $(go list ./... | grep -v /tests/e2e)

  e2e-test:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Test
        run: make test-e2e-full