name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - "master"

jobs:
  image-build:
    runs-on: ubuntu-24.04
    steps:
      - name: build
        uses: RedSockActions/release_image@v1.0.29
        with:
          DRYRUN: true
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}

  tag-release:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    needs:
      - image-build
    steps:
      - name: Release tag
        id: release
        uses: RedSockActions/release_tag@v1.1.6
        with:
          token: ${{ github.token }}
    outputs:
      tag: ${{ steps.release.outputs.tag }}

  registry_release:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    needs:
      - tag-release
    steps:
      - name: Release image
        if: ${{ needs.tag-release.outputs.tag != '' }}
        uses: RedSockActions/release_image@v1.0.29
        with:
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PWD: ${{ secrets.REGISTRY_PWD }}

  npm-registry-release:
    if: ${{ needs.tag-release.outputs.tag != '' }}
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    needs:
      - tag-release
    steps:
      - name: Release image
        uses: RedSockActions/release_npm_package@v0.0.4
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VERSION: ${{ needs.tag-release.outputs.tag }}
          WORKING_DIRECTORY: pkg/web/@vervstack/velez
  init-script-release:
    if: ${{ needs.tag-release.outputs.tag != '' }}
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    needs:
      - tag-release
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Making script
        run: |
          VERSION="${{ needs.tag-release.outputs.tag }}"
          cp scripts/prod_init.sh.pattern scripts/init_node.sh
          sed -i "s/{{ .Version }}/${VERSION}/g" scripts/init_node.sh
      - name: Upload to s3
        uses: marverlous811/minio-upload@v1.2.0
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: 'verv'
          local_path: './scripts/init_node.sh'
          remote_path: '/scripts/'
